### PR TITLE
Fix bug in TrimShape 

### LINKED ISSUE #1933: Issues with Uturns at Via locations
Uturns are allowed at locations with type = "via". However, there is no maneuver generated at such points - leading to confusing instructions. In addition, it appears that the returned shape is missing one direction leading to/from the Uturn from the last node/intersection.

This request shows the problem:
{"locations":[{"lat":39.660558,"lon":-76.157187},{"lat":39.665125,"lon":-76.165207, "type":"via"},{"lat":39.660430,"lon":-76.154769}],"costing":"bicycle"}

### PR DESCRIPTION
**Pull request by dnesbitt61**
If start_vertex is not valid it never trims the start of the shape but accumulates the along distance and never resets it. This leads to erasing most of the shape when clipping after the end point. The fix is to not trim start shape if the start_vertex is not valid since it can never actually erase any of the
shape in this case. Similarly for trimming past the end shape.

# Issue

fixes #1933 

## Tasklist

 - [ ] Add tests
 - [x] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

### CODE REVIEW

File: src/thor/triplegbuilder.cc [hunk 1]
```diff
@@ -35,32 +35,38 @@ void TrimShape(std::vector<PointLL>& shape,
...
-  while (current != shape.end() - 1) {
-    along += (current + 1)->Distance(*current);
-    // just crossed it
-    if ((along > start) && start_vertex.IsValid()) {
-      along = start;
-      *current = start_vertex;
-      shape.erase(shape.begin(), current);
-      break;
+  if (start_vertex.IsValid()) {
+    while (current != shape.end() - 1) {
```
Comment (kevinkreiser) [inline src/thor/triplegbuilder.cc]: why not add the condition to the while loop to reduce the indentation and the diff?

Comment (dnesbitt61) [reply src/thor/triplegbuilder.cc]: start_vertex never changes inside the loop so why recheck it over the entire shape?

Comment (dnesbitt61) [reply src/thor/triplegbuilder.cc]: I could add this after the first loop: 
  // return if end vertex is not valid
  if (!end_vertex.IsValid()) {
    return;
  }

that would reduce some diffs

Comment (kevinkreiser) [reply src/thor/triplegbuilder.cc]: because branch prediction makes it pretty much free and its easier to read. was just a nit pick nothing too pressing

Comment (dnesbitt61) [reply src/thor/triplegbuilder.cc]: this logic (and similar logic for "partial" shape) has always been tricky. I wanted to add some comments around it and make it clearer.
