### PR TITLE
Too strict requirements on u-turns

### LINKED ISSUE #1982: Too strict requirements on u-turns
In the linked route below, Valhalla fails in providing a route due to not adequately allowing for a u-turn on Quay St.
http://valhalla.github.io/demos/routing/index-internal.html#loc=19,51.455433,-2.595520&locations=[{%22lat%22:51.45552952902732,%22lon%22:-2.594244182055263},{%22lat%22:51.455145118493185,%22lon%22:-2.5958588718822284}]&costing=%22auto%22&directionsoptions={%22language%22:%22en-US%22}

Quay St, Bristol UK, converts into an outward flowing one-way street. In order to arrive at the destination, a U-turn is required on Quay st. Valhalla does not do a u-turn since that's only allowed when at a complete dead-end today.

A solution might be to allow for u-turns in more locations by relaxing the requirements in the `Allowed`/`AllowedReverse` function in `sif/autocost.cc`.  In the case of the _reverse_ route expansion of Quay st, in reality it actually is a dead-end due to the conversion into a one-way street.

To resolve this, the deadend flag could be expanded to differentiate between outgoing `deadend` via “is this node able to enter more than one outgoing edge” as well as an incoming `reverse_deadend` meaning “Is more than one opposing node able to enter this node”.

Another solution would be to calculate the concept of `deadend` and `reverse_deadend` at runtime which would allow for a more dynamic notion of what a deadend is. Time of day and routing profile may influence this, for example.

In the case of the Whitelion route failure, a correct `reverse_deadend` would mean that the _reverse_ expanding A* would detect a deadend and make a u-turn, resulting in a route found.

### PR DESCRIPTION
**Pull request by PureW**
# Issue

 feat(thor): Adds runtime check of whether an edge is a deadend

This allows for time dependence of deadend-detection as well as resolving an issue
where a path only is a deadend in the reverse expansion of
bidirectional_astar.

Fixes #1982

## Performance hit

The bidirectional a-star takes a performance hit from this change. This is due to two reasons:

 1) Evaluating whether something is a deadend at runtime rather than using the pre-computed deadend bit. _We managed to write this runtime check inside the existing loop which we believe make this check basically a no-change to performance compared to the naive check._
 2) Actually relaxing the requirements for a u-turn means that more nodes will be expanded in the search.

I ran a few benchmarks on the common cross-country trip. I split the PR into two major commits. The first one simply refactors the `Expand*` functions and puts the loop contents into `Expand*Inner` functions to improve clarity of code. Logic should still be same as in `master`.

The second commit actually switches to the runtime detection of deadends. This is just a few lines of change from the previous commit in order to avoid ascribing too much of the performance hit to the refactor:

Benchmarked using cross-country route:
```fish
./valhalla_run_route \
  --config ~/data/valhalla.json \
  --multi-run 100 \
    -j '{"locations":[{"lat":32.697958,"lon":-117.174648, "street":"Park Boulevard"},{"lat":40.042553,"lon":-76.299115}],"costing":"auto"}' \
  | tee result \
  | grep average
```

```fish
New performance numbers

  derived_deadend (git:3c6439e51)

    #1 PathAlgorithm GetBestPath average: 196 ms
    #2 PathAlgorithm GetBestPath average: 201 ms

  Refactored Expand* functions but still same logic as in master (git:4432b4a8c)

    #1 PathAlgorithm GetBestPath average: 197 ms
    #2 PathAlgorithm GetBestPath average: 199 ms

  master (git:b14999693)

    #1 PathAlgorithm GetBestPath average: 183 ms
    #2 PathAlgorithm GetBestPath average: 184 ms

```

**Expanding more edges due to more deadends seem to carry a ~9% increase in wall-clock time on cross country route on my laptop**. 

## Open questions

If we go ahead with this change, the time-dependant a-star should probably be updated to use this logic as well.

## Tasklist

 - [] Add tests (Some added, investigating adding more)
 - [x] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by dnesbitt61** [comment]
that is pretty serious performance reduction. Did you test with any pedestrian or bicycle routes to see what impact is seen there? Pedestrian basically allows Uturns anywhere so I assume there should be no change there. 
Did you look into stats on how large the increase in path iterations was (combined size of the edge labels - logged in FormPath)? Did you see roughly 50% more EdgeLabels?

**Comment by PureW** [comment]
> Did you look into stats on how large the increase in path iterations was (combined size of the edge labels - logged in FormPath)? Did you see roughly 50% more EdgeLabels?

@dnesbitt61 I updated the post above. Seems like roughly 70% more path-iterations are made with this change.

I've yet to investigate walking/bike routes. Working on those.

**Comment by PureW** [comment]
> that is pretty serious performance reduction. Did you test with any pedestrian or bicycle routes to see what impact is seen there? Pedestrian basically allows Uturns anywhere so I assume there should be no change there.

I updated the numbers above with a longer bike route. You're correct that the extra expansion does not seem to happen for the bike case.

> Did you look into stats on how large the increase in path iterations was (combined size of the edge labels - logged in FormPath)? Did you see roughly 50% more EdgeLabels?

Seemingly some 70% extra path iterations are done on the cross-country auto route.

File: src/thor/bidirectional_astar.cc [hunk 1]
```diff
@@ -97,10 +111,33 @@ void BidirectionalAStar::Init(const PointLL& origll, const PointLL& destll) {
...
+  EdgeStatusInfo* edge_status;
+
+  static EdgeMetadata make(const GraphId& node,
+                           const NodeInfo* nodeinfo,
+                           const GraphTile* tile,
+                           EdgeStatus& edge_status_) {
+    GraphId edge_id = {node.tileid(), node.level(), nodeinfo->edge_index()};
+    EdgeStatusInfo* edge_status = edge_status_.GetPtr(edge_id, tile);
+    const DirectedEdge* directededge = tile->directededge(edge_id);
+    return {.edge = directededge, .edge_id = edge_id, .edge_status = edge_status};
```
Comment (mloskot) [inline src/thor/bidirectional_astar.cc]: The designated initializer is C++20 features. You need to make it C++11 using list or direct initialization.

File: src/baldr/graphtile.cc [hunk 2]
```diff
@@ -514,7 +514,7 @@ iterable_t<const DirectedEdge> GraphTile::GetDirectedEdges(const GraphId& node)
     return GetDirectedEdges(nodeinfo);
   }
   throw std::runtime_error(
-      "GraphTile NodeInfo index out of bounds: " + std::to_string(node.tileid()) + "," +
+      "GraphTile NodeInfo index out of bounds 4: " + std::to_string(node.tileid()) + "," +
```
Comment (kevinkreiser) [inline src/baldr/graphtile.cc]: would a line number macro be better here for differentiation? what do 4 and 5 refer to anyway?

File: test/CMakeLists.txt [hunk 3]
```diff
@@ -52,11 +52,20 @@ add_custom_command(OUTPUT ${CMAKE_BINARY_DIR}/test/data/utrecht_tiles/0/003/196.
 #  COMMAND ${CMAKE_BINARY_DIR}/valhalla_add_predicted_traffic
 #      --inline-config '{"mjolnir":{"tile_dir":"test/data/utrecht_tiles","hierarchy":true,"shortcuts":true,"concurrency":4,"logging":{"type":""}}}'
 #      -t ${VALHALLA_SOURCE_DIR}/test/data/
-  COMMENT "Building Utrecht Tiles..."
+  COMMENT "Building Whitelion Tiles..."
```
Comment (kevinkreiser) [inline test/CMakeLists.txt]: accidental im guessing

File: test/bidirectional_astar.cc [hunk 4]
```diff
@@ -0,0 +1,231 @@
...
+} // namespace
+
+int main() {
+  // TODO The below call builds the tiles, but the test fails when this runs.
+  // Test passes the _next_ time after tiles were built...
+  // Disk syncing issues? Race condition?
+  // Current workaround is to build tiles separately as a input artifact in CMake
+  // build_tiles(get_conf());
+
+  test::suite suite("bidirectional-a-star-whitelion");
```
Comment (kevinkreiser) [inline test/bidirectional_astar.cc]: what is this hyphen non-sense? :smile:

File: valhalla/thor/bidirectional_astar.h [hunk 5]
```diff
@@ -119,20 +121,37 @@ class BidirectionalAStar : public PathAlgorithm {
    */
   void ExpandForward(baldr::GraphReader& graphreader,
                      const baldr::GraphId& node,
-                     const sif::BDEdgeLabel& pred,
+                     sif::BDEdgeLabel& pred,
                      const uint32_t pred_idx,
                      const bool from_transition);
+  // Private helper function for `ExpandForward`
+  bool ExpandForwardInner(baldr::GraphReader& graphreader,
```
Comment (kevinkreiser) [inline valhalla/thor/bidirectional_astar.h]: have you tried forcing these to be inlined to get back the 15% drop you had from the refactor?

File: src/thor/bidirectional_astar.cc [hunk 6]
```diff
@@ -11,6 +15,16 @@ using namespace valhalla::sif;
 namespace valhalla {
 namespace thor {
 
+std::string get_shape(GraphReader& graphreader, const GraphId& edgeid) {
```
Comment (PureW) [inline src/thor/bidirectional_astar.cc]: TODO Remove this.

File: src/thor/bidirectional_astar.cc (hunk 1 above)
Comment (kevinkreiser) [reply src/thor/bidirectional_astar.cc]: this seems to be an interesting exception! apparently in c++11 "trivial" designated intializers are supported. "trivial" apparently means you specify all members of the struct and all are in the same order as they are in the structs declaration. so for example this works even without c++11 at least in gcc:

```
struct foo{
  int bar;
  int baz;
};
int main(){
  foo f={.bar=3,.baz=7};
  return 0;
}
```
but this does not:

```
struct foo{
  int bar;
  int baz;
};
int main(){
  foo f={.baz=3,.bar=7};
  return 0;
}
```

In the end i do agree its probably not a good idea to start using this syntax if we can only use special case. i'm pretty sure this would also be the only example of this usage in the entire project. i know its less clear but without the designators is probably the way to go

File: src/thor/bidirectional_astar.cc [hunk 7]
```diff
@@ -202,10 +198,96 @@ void BidirectionalAStar::ExpandForward(GraphReader& graphreader,
...
+                                            const GraphTile* tile) {
+  // Skip shortcut edges until we have stopped expanding on the next level. Use regular
+  // edges while still expanding on the next level since we can still transition down to
+  // that level. If using a shortcut, set the shortcuts mask. Skip if this is a regular
+  // edge superseded by a shortcut.
+  if (meta.edge->is_shortcut()) {
+    if (hierarchy_limits_forward_[meta.edge_id.level() + 1].StopExpanding()) {
+      shortcuts |= meta.edge->shortcut();
+    } else {
+      return false;
```
Comment (PureW) [inline src/thor/bidirectional_astar.cc]: TODO How does shortcuts affect the u-turn expansion?

File: src/thor/bidirectional_astar.cc [hunk 8]
```diff
@@ -202,10 +198,96 @@ void BidirectionalAStar::ExpandForward(GraphReader& graphreader,
...
+    return false;
+  }
+
+  // Skip this edge if edge is permanently labeled (best path already found
+  // to this directed edge), if no access is allowed (based on costing method),
+  // or if a complex restriction prevents transition onto this edge.
+  bool is_allowed = costing_->Allowed(meta.edge, pred, tile, meta.edge_id, 0, 0);
+  bool is_restricted =
+      costing_->Restricted(meta.edge, pred, edgelabels_forward_, tile, meta.edge_id, true);
+  if (meta.edge_status->set() == EdgeSet::kPermanent || !is_allowed || is_restricted) {
```
Comment (PureW) [inline src/thor/bidirectional_astar.cc]: Some of the refactor performance drop may come from `is_allowed`/`is_restricted` being evaluated every time instead of using the early return function of ` ... || ... `.

File: src/thor/bidirectional_astar.cc [hunk 9]
```diff
@@ -375,6 +503,10 @@ BidirectionalAStar::GetBestPath(valhalla::Location& origin,
         // result in other connections.
         if (edgestatus_reverse_.Get(fwd_pred.opp_edgeid()).set() == EdgeSet::kPermanent) {
           if (SetForwardConnection(graphreader, fwd_pred)) {
+            // std::cout << "$$$$$$$$$$$$$$$$$$$$$$$   SetForwardConnection "
```
Comment (PureW) [inline src/thor/bidirectional_astar.cc]: TODO Cleanup.

File: src/thor/bidirectional_astar.cc [hunk 10]
```diff
@@ -405,6 +537,10 @@ BidirectionalAStar::GetBestPath(valhalla::Location& origin,
         // result in other connections.
         if (edgestatus_forward_.Get(rev_pred.opp_edgeid()).set() == EdgeSet::kPermanent) {
           if (SetReverseConnection(graphreader, rev_pred)) {
+            // std::cout << "$$$$$$$$$$$$$$$$$$$$$$$   SetReverseConnection "
```
Comment (PureW) [inline src/thor/bidirectional_astar.cc]: TODO Cleanup.

File: src/thor/worker.cc [hunk 11]
```diff
@@ -104,7 +104,7 @@ thor_worker_t::work(const std::list<zmq::message_t>& job,
   // get time for start of request
   auto s = std::chrono::system_clock::now();
   auto& info = *static_cast<prime_server::http_request_info_t*>(request_info);
-  LOG_INFO("Got Thor Request " + std::to_string(info.id));
+  LOG_INFO("Got Thor Request" + std::to_string(info.id));
```
Comment (PureW) [inline src/thor/worker.cc]: TODO Restore space.

File: valhalla/thor/bidirectional_astar.h (hunk 5 above)
Comment (PureW) [reply valhalla/thor/bidirectional_astar.h]: I did, did not see any measurable change.

File: test/CMakeLists.txt (hunk 3 above)
Comment (PureW) [reply test/CMakeLists.txt]: yup.

File: src/baldr/graphtile.cc (hunk 2 above)
Comment (PureW) [reply src/baldr/graphtile.cc]: :+1: Line number sounds much better. 4 and 5 refers to this being the fourth and fifth version of this exception I tracked down when debugging.

File: src/thor/bidirectional_astar.cc (hunk 1 above)
Comment (mloskot) [reply src/thor/bidirectional_astar.cc]: @kevinkreiser 
> apparently in c++11 and earlier "trivial" designated intializers are supported. 

No, it is not, I'm afraid.

What you are observing with GCC and clang is C99 feature that kicks in by default.
If C99 is disabled e.g. `-std=c++11 -pedantic` then that program will fail to compile 

- GCC 9

```
warning: C++ designated initializers only available with '-std=c++2a' or '-std=gnu++2a' [-Wpedantic]
   foo f={.bar=3,.baz=7};
          ^
```

- clang 9

```
warning: designated initializers are a C99 feature [-Wc99-extensions]
  foo f={.bar=3,.baz=7};
         ^~~~~~
```

MSVC does not support C99 features for C itself. It only supports C99 features that are part of C++11 or later versions of C++.

Comment (kevinkreiser) [reply src/thor/bidirectional_astar.cc]: yeah that is why i said "at least in gcc" because i had suspected it wasnt the case with all compilers. thanks for the confirmation!

File: src/thor/bidirectional_astar.cc (hunk 8 above)
Comment (kevinkreiser) [reply src/thor/bidirectional_astar.cc]: ah wow i didnt even notice this, good catch, we should avoid as much as possible extra costing calls

File: src/thor/bidirectional_astar.cc (hunk 1 above)
Comment (PureW) [reply src/thor/bidirectional_astar.cc]: Adjusted code.

File: test/bidirectional_astar.cc (hunk 4 above)
Comment (PureW) [reply test/bidirectional_astar.cc]: name has been non-hyphenated :)

File: src/baldr/graphtile.cc (hunk 2 above)
Comment (PureW) [reply src/baldr/graphtile.cc]: Switched to file:line-number.

**Comment by dnesbitt61** [comment]
numbers look a lot better! I couldn't think of how a few more dead-end cases could cause such a dramatic increase.

**Comment by PureW** [comment]
Performance is hard. I've rerun benches this morning on my i7 desktop at home that doesn't do funny things like thermal throttling or adjusting schedulers depending on battery levels etc.

Inlinining the `ExpandXXXInner` functions _does_ seem to make a difference on that cpu/computer.I now measured 136ms vs 142ms, a 4% overhead with new code: https://github.com/valhalla/valhalla/pull/2018/commits/53b661c7df6281bd916bfdda9150a2abf5fcae6d

cc @dnesbitt61
