### PR TITLE
Fix PointXY::ClosestPoint to compile on GCC 12.2

### LINKED ISSUE #3727: Werror=maybe-uninitialized in midgard/point2.cc
When building valhalla from source with GCC 12.2 I'm getting a Werror=maybe-uninitialized in midgard/point2.cc:

```
In file included from /usr/include/c++/12.2.0/functional:54,
                 from ./valhalla/valhalla/midgard/point2.h:6,
                 from ./valhalla/src/midgard/point2.cc:1:
In constructor 'constexpr std::_Head_base<_Idx, _Head, false>::_Head_base(_UHead&&) [with _UHead = int; long unsigned int _Idx = 2; _Head = int]',
    inlined from 'constexpr std::_Tuple_impl<_Idx, _Head>::_Tuple_impl(_UHead&&) [with _UHead = int; long unsigned int _Idx = 2; _Head = int]' at /usr/include/c++/12.2.0/tuple:441:38,
    inlined from 'constexpr std::_Tuple_impl<_Idx, _Head, _Tail ...>::_Tuple_impl(_UHead&&, _UTail&& ...) [with _UHead = float; _UTail = {int}; <template-parameter-2-3> = void; long unsigned int _Idx = 1; _Head = float; _Tail = {int}]' at /usr/include/c++/12.2.0/tuple:292:38,
    inlined from 'constexpr std::_Tuple_impl<_Idx, _Head, _Tail ...>::_Tuple_impl(_UHead&&, _UTail&& ...) [with _UHead = valhalla::midgard::PointXY<float>; _UTail = {float, int}; <template-parameter-2-3> = void; long unsigned int _Idx = 0; _Head = valhalla::midgard::PointXY<float>; _Tail = {float, int}]' at /usr/include/c++/12.2.0/tuple:292:38,
    inlined from 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {valhalla::midgard::PointXY<float>, float, int}; bool _Valid = true; typename std::enable_if<_TCC<_Valid>::__is_implicitly_constructible<_UElements ...>(), bool>::type <anonymous> = true; _Elements = {valhalla::midgard::PointXY<float>, float, int}]' at /usr/include/c++/12.2.0/tuple:744:54,
    inlined from 'constexpr std::tuple<typename std::__strip_reference_wrapper<typename std::decay<_Elements>::type>::__type ...> std::make_tuple(_Elements&& ...) [with _Elements = {valhalla::midgard::PointXY<float>, float, int}]' at /usr/include/c++/12.2.0/tuple:1581:62,
    inlined from 'std::tuple<valhalla::midgard::PointXY<PrecisionT>, PrecisionT, int> valhalla::midgard::PointXY<PrecisionT>::ClosestPoint(const std::vector<valhalla::midgard::PointXY<PrecisionT> >&) const [with PrecisionT = float]' at ./valhalla/src/midgard/point2.cc:106:91:
/usr/include/c++/12.2.0/tuple:200:11: error: 'idx' may be used uninitialized [-Werror=maybe-uninitialized]
  200 |         : _M_head_impl(std::forward<_UHead>(__h)) { }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./valhalla/src/midgard/point2.cc: In member function 'std::tuple<valhalla::midgard::PointXY<PrecisionT>, PrecisionT, int> valhalla::midgard::PointXY<PrecisionT>::ClosestPoint(const std::vector<valhalla::midgard::PointXY<PrecisionT> >&) const [with PrecisionT = float]':
./valhalla/src/midgard/point2.cc:36:7: note: 'idx' was declared here
   36 |   int idx;                    // Index of closest segment so far
      |       ^~~
In constructor 'constexpr std::_Head_base<_Idx, _Head, false>::_Head_base(_UHead&&) [with _UHead = int; long unsigned int _Idx = 2; _Head = int]',
    inlined from 'constexpr std::_Tuple_impl<_Idx, _Head>::_Tuple_impl(_UHead&&) [with _UHead = int; long unsigned int _Idx = 2; _Head = int]' at /usr/include/c++/12.2.0/tuple:441:38,
    inlined from 'constexpr std::_Tuple_impl<_Idx, _Head, _Tail ...>::_Tuple_impl(_UHead&&, _UTail&& ...) [with _UHead = double; _UTail = {int}; <template-parameter-2-3> = void; long unsigned int _Idx = 1; _Head = double; _Tail = {int}]' at /usr/include/c++/12.2.0/tuple:292:38,
    inlined from 'constexpr std::_Tuple_impl<_Idx, _Head, _Tail ...>::_Tuple_impl(_UHead&&, _UTail&& ...) [with _UHead = valhalla::midgard::PointXY<double>; _UTail = {double, int}; <template-parameter-2-3> = void; long unsigned int _Idx = 0; _Head = valhalla::midgard::PointXY<double>; _Tail = {double, int}]' at /usr/include/c++/12.2.0/tuple:292:38,
    inlined from 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {valhalla::midgard::PointXY<double>, double, int}; bool _Valid = true; typename std::enable_if<_TCC<_Valid>::__is_implicitly_constructible<_UElements ...>(), bool>::type <anonymous> = true; _Elements = {valhalla::midgard::PointXY<double>, double, int}]' at /usr/include/c++/12.2.0/tuple:744:54,
    inlined from 'constexpr std::tuple<typename std::__strip_reference_wrapper<typename std::decay<_Elements>::type>::__type ...> std::make_tuple(_Elements&& ...) [with _Elements = {valhalla::midgard::PointXY<double>, double, int}]' at /usr/include/c++/12.2.0/tuple:1581:62,
    inlined from 'std::tuple<valhalla::midgard::PointXY<PrecisionT>, PrecisionT, int> valhalla::midgard::PointXY<PrecisionT>::ClosestPoint(const std::vector<valhalla::midgard::PointXY<PrecisionT> >&) const [with PrecisionT = double]' at ./valhalla/src/midgard/point2.cc:106:91:
/usr/include/c++/12.2.0/tuple:200:11: error: 'idx' may be used uninitialized [-Werror=maybe-uninitialized]
  200 |         : _M_head_impl(std::forward<_UHead>(__h)) { }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./valhalla/src/midgard/point2.cc: In member function 'std::tuple<valhalla::midgard::PointXY<PrecisionT>, PrecisionT, int> valhalla::midgard::PointXY<PrecisionT>::ClosestPoint(const std::vector<valhalla::midgard::PointXY<PrecisionT> >&) const [with PrecisionT = double]':
./valhalla/src/midgard/point2.cc:36:7: note: 'idx' was declared here
   36 |   int idx;                    // Index of closest segment so far
      |       ^~~
```

### PR DESCRIPTION
**Pull request by sl4b**
# Issue

Fixes #3727.

I solved the actual uninitialized value problem that @kevinkreiser mentioned and initialized `idx` to 0 so that GCC 12.2 won't error anymore.

I think it's fine to initialize `idx` to 0 to make GCC stop erroring because the `closest` variable already starts with an initial value and always gets assigned a new value at the same time as `idx`... in the case that the for loop completes without changing `idx` from 0, it also won't have changed `closest` from its initial value. The function would have already been returning a potentially wrong result by using this initial value for `closest`. In other words, the assumptions made by this updated version of the function are no different than before.

## Tasklist

 - [ ] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

File: src/midgard/point2.cc [hunk 1]
```diff
@@ -47,8 +47,9 @@ PointXY<PrecisionT>::ClosestPoint(const std::vector<PointXY<PrecisionT>>& pts) c
     const PointXY<PrecisionT>& p1 = pts[index + 1];
 
     // Construct vector v1 - represents the segment.  Skip 0 length segments
+    // that are not at the end of the line.
     v1.Set(p0, p1);
-    if (v1.x() == 0.0f && v1.y() == 0.0f) {
+    if (v1.x() == 0.0f && v1.y() == 0.0f && index < pts.size() - 2) {
```
Comment (sl4b) [inline src/midgard/point2.cc:52]: It's worth mentioning also that this change shouldn't break the algorithm. When we hit a 0 length segment at the end of the polyline and continue through the for loop, we know that `v1` is the zero vector. So on line 62, `dot` will equal 0. This causes the if statement starting on line 63 to have a true condition, and the things done in that if statement are what the algorithm should already be doing in this case.

**Review by kevinkreiser — APPROVED** [review]
