### PR TITLE
fix trip leg builder DirectedEdge index out of bounds - #1831

### LINKED ISSUE #1831: GraphTile DirectedEdge index out of bounds
Hi all,

Some of the requests that would previously works ok (v2.6-2.7) seems to trigger an index out of bounds on 3.0.x.

This seems to happen for multimodal costing (see json below). From the log information it seems that a route is properly found (I have a LOG_INFO statement at the end of multimodal.cc / `FormPath` ), so the crash happens later: in the generation of the response?

I've tested my own branch, 3.0.3 and master and have the exact same issue. I was first thinking of an issue with the underlying routing graph, maybe due to some invalid/incomplete GTFS data from transit.land but seems a path has been found so I think it is not the case.

Any help? 

Execution log on latest master
```#033[32;1m[INFO]#033[0m Got Loki Request 9
[ANALYTICS] locations_count::2
[ANALYTICS] costing_type::multimodal
[ANALYTICS] total_location_distance::45.022793km
#033[32;1m[INFO]#033[0m Got Thor Request 9
[ANALYTICS] travel_mode::1
#033[31;1m[ERROR]#033[0m PointLL::HeadingAlongPolyline has < 2 vertices
#033[31;1m[ERROR]#033[0m PointLL::HeadingAtEndOfPolyline has < 2 vertices
[ANALYTICS] 400::GraphTile DirectedEdge index out of bounds: 786985,3,2137 directededgecount= 2080
```
request
```json
{"locations":[{"lat":46.712399206206,"lon":6.37056453497152,"type":"break","radius":100.0},{"lat":46.8196384138731,"lon":6.93988082951435,"type":"break","radius":100.0}],"costing":"multimodal","costing_options":{"pedestrian":{"transit_transfer_max_distance":900.0,"transit_start_end_max_distance":900.0,"walking_speed":4.5},"transit":{"use_bus":0.5,"use_rail":0.5,"use_transfers":0.5,"transfer_cost":15,"transfer_penalty":300,"filters":{"operators":{"ids":[],"action":"exclude"},"routes":{"ids":[],"action":"exclude"}}}},"directions_options":{"language":"en-US","units":"km"},"date_time":{"value":"2019-05-29T11:05","type":1}}
```

### PR DESCRIPTION
**Pull request by slvlirnoff**
# Issue

Attempt to fix random crash when building trip leg with transit data. 
Seems to fixes #1831

## Tasklist

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

File: src/thor/triplegbuilder.cc [hunk 1]
```diff
@@ -1180,14 +1180,16 @@ TripLegBuilder::Build(const AttributesController& controller,
...
-    if (t2 == nullptr) {
-      continue;
+    if (!directededge->IsTransitLine()) {
+      // Save the opposing edge as the previous DirectedEdge (for name consistency)
+      const GraphTile* t2 =
+          directededge->leaves_tile() ? graphreader.GetGraphTile(directededge->endnode()) : graphtile;
+      if (t2 == nullptr) {
+        continue;
+      }
+      GraphId oppedge = t2->GetOpposingEdgeId(directededge);
```
Comment (kevinkreiser) [inline src/thor/triplegbuilder.cc]: @slvlirnoff we can make this a much smaller diff, instead of wrapping all this with an `if`. right after you try to get the opposing edge id, you should be able to check that `oppedge.Is_Valid()` is `true` before using it.
