### PR TITLE
Removed cache lock. It's synchronized inside.

### LINKED ISSUE #5598: Speedup of elevation processing from compressed tiles.
In my pipeline I use LZ4 compressed elevation tiles. While checking crash from #5597 I've noticed that it works on one thread no matter what. It appears that there is a lock one level above that tile cache. cache::get() locks cache_lck. And then inside of the `cache_t` it locks mutex.

I suggest to remove cache_lck completely since `cache_t` is already protected by internal mutex. I can submit a pull request from https://github.com/GLMap/valhalla/commit/960d0df4b618e821ae521293be5f40e91e04a16c

### PR DESCRIPTION
**Pull request by molind**
# Issue

Speedup of elevation decompression. Removed redundant lock. Fixes #5598.

## Tasklist

 - [ ] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too
 - [ ] If you made changes to a translation file, [update transifex](docs/docs/locales.md) too

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

File: src/skadi/sample.cc [hunk 1]
```diff
@@ -446,7 +446,6 @@ template <class coord_t> double sample::get(const coord_t& coord, tile_data& til
   // the caller can pass a cached tile, so we only fetch one if its not the one they already have
   if (index != tile.get_index()) {
     {
-      std::lock_guard<std::mutex> _(cache_lck);
```
Comment (kinkard) [inline src/skadi/sample.cc:449]: Maybe I'm reading it wrong, but it looks like that with this change, the following piece of code should be guarded: https://github.com/valhalla/valhalla/blob/3a21fe74cf340e9195c9f34847051b01b4ff0e7f/src/skadi/sample.cc#L328-L333

Maybe https://en.wikipedia.org/wiki/Double-checked_locking could be used here.

Comment (molind) [reply src/skadi/sample.cc:449]: Yeah. That would be better. And without multiple memory maps one on top of another.
