### PR TITLE
fix DST sensitive transit test

### LINKED ISSUE #4363: Another flaky transit test
don't know why exactly now, but the tests are still flaky with off-by-one-hour. sounds very much like DST, but that's not due for another week in toronto.

### PR DESCRIPTION
**Pull request by nilsnolde**
fixes #4363

### CODE REVIEW

File: test/gurka/test_gtfs.cc [hunk 1]
```diff
@@ -928,15 +928,27 @@ TEST(GtfsExample, route_trip1) {
...
+  auto dep_time = transit_info.transit_stops(0).departure_date_time();
+  dep_time.erase(dep_time.rfind("-") + 1);
+  std::string dep_time_json = ti_json["transit_stops"][0]["departure_date_time"].GetString();
+  dep_time_json.erase(dep_time_json.rfind("-") + 1);
+
+  EXPECT_EQ(dep_time, req_time);
+  EXPECT_EQ(dep_time_json, req_time);
+
+  // determine the right arrival datetimes, keep the timezone "+"
+  req_time.replace(req_time.find('T') + 1, 6, "07:06-");
```
Comment (nilsnolde) [inline test/gurka/test_gtfs.cc:943]: I admit I didn't really contribute to the legibility of the test, but the rest is similarly ugly (though also partly my fault) :smile: 

Does trigger me to look into https://github.com/valhalla/valhalla/issues/4241 while I'm at it..

**Review by kevinkreiser — APPROVED** [review]

**Comment by nilsnolde** [comment]
sorry @kevinkreiser a few typos, which dismissed your review.. can you approve again?

**Review by kevinkreiser — APPROVED** [review]
