### PR TITLE
use a singleton pattern to register the gdal driver once in one place

### LINKED ISSUE #4623: GeoTIFF segfaulting on Mac ARM python bindings
Thought I'd try out this new GeoTIFF feature on Mac ARM.

I'm running it through python bindings so I can't get a lot of debugging info.

Has anyone successfully ran this on an ARM build of any kind?

I'm doing regular isochrone request (which works), with "format":"geotiff" added

### PR DESCRIPTION
**Pull request by kevinkreiser**
fixes #4623 (hopefully)

### CODE REVIEW

File: src/tyr/isochrone_serializer.cc [hunk 1]
```diff
@@ -169,7 +186,7 @@ std::string serializeGeoTIFF(Api& request, const std::shared_ptr<const GriddedDa
   char** geotiff_options = NULL;
   geotiff_options = CSLSetNameValue(geotiff_options, "COMPRESS", "PACKBITS");
 
-  // TODO: check if there's an easy way to only instantiate the driver once
+  gdal_singleton_t::get();
```
Comment (kevinkreiser) [inline src/tyr/isochrone_serializer.cc:189]: this first time this is called (per process) the constructor above is called and the driver registration happens. subsequent calls are no-ops

File: CMakeLists.txt [hunk 2]
```diff
@@ -191,12 +191,15 @@ else()
   message(FATAL_ERROR "Required target protobuf::libprotobuf-lite or protobuf::libprotobuf is not defined")
 endif()
 
-# gdal
-set(gdal_target "")
+# unless you said you didnt want gdal we try to turn it on, if we cant we tell you
```
Comment (kevinkreiser) [inline CMakeLists.txt:194]: i thought it would be better to default turning it ON if we can and if we couldnt we simply report that was the case. if you tell it you definitely dont want it by setting it to OFF then we dont even try

**Review by nilsnolde — COMMENTED** [review]
Great, thanks. Just one question about GDAL=OFF @kevinkreiser . Could even do one CI build without, but no need to either IMO

File: CMakeLists.txt (hunk 2 above)
Comment (kevinkreiser) [reply CMakeLists.txt:194]: yep will do that real quick

**Review by nilsnolde — APPROVED** [review]

File: src/tyr/CMakeLists.txt [hunk 3]
```diff
@@ -20,7 +20,7 @@ set(system_includes
   ${date_include_dir}
   $<$<BOOL:${WIN32}>:${dirent_include_dir}>)
 
-
+set(tyr_dependencies )
```
Comment (nilsnolde) [inline src/tyr/CMakeLists.txt:23]: I guess this is accidental @kevinkreiser ?

**Review by nilsnolde — CHANGES_REQUESTED** [review]
I think I approved from my phone, just seeing one nitty thing. also, can you remove the gtiff driver loading thing in the isochrone.cc? once that's gone, we know this PR works for the actor.

**Comment by kevinkreiser** [comment]
> can you remove the gtiff driver loading thing in the isochrone.cc test

ha! yeah i grepped the `include` and `src` directories but forgot to grep `test`!

**Comment by nilsnolde** [comment]
Oh jeez I’m really sorry, lousy review: I forgot about the docs in docs/docs/building.md, they still say default is OFF. 

Anyways no worries if you don’t feel like it

File: test/isochrone.cc [hunk 4]
```diff
@@ -355,7 +355,6 @@ void check_raster_edges(size_t x, size_t y, uint16_t* data) {
 }
 
 TEST(Isochrones, test_geotiff_output_distance) {
-  GDALRegister_GTiff();
```
Comment (kevinkreiser) [inline test/isochrone.cc:358]: i dont really like removing these because the tests themselves use gdal directly to load the response from the library. now in this case technically we can remove them because hidden in the source of the serializer we are doing this initialization but the tests (and just in general any calling code) shouldnt know/assume that its preconditions are met by something it calls into. the only way to get around this would be to expose gdal initialization as a public api in the library and have the tests call that but i hate that idea even worse.

Comment (nilsnolde) [reply test/isochrone.cc:358]: Ah I didn’t check that.. I kinda assumed those driver inits were there to make the test work (it wouldn’t have without). That’s true.. anyways, the alternative to test this bit is indeed worse.

**Review by nilsnolde — APPROVED** [review]

File: test/isochrone.cc (hunk 4 above)
Comment (kevinkreiser) [reply test/isochrone.cc:358]: the other idea is to leave them there though what i would do is in the suite initialization call it once

Comment (nilsnolde) [reply test/isochrone.cc:358]: Both is fine with me tbh, I get your point, but also think it’ll be fine probably forever ®
