### PR TITLE
Fix bug with trivial paths on oneway edges. 

### LINKED ISSUE #1359: Driving in backward direction on oneway streets
If source and target points are on the same one-directional way than Valhalla can return a route that allows to drive in backward direction. 

Example: https://www.openstreetmap.org/way/593719541
* Correct  `routing/index-internal.html#loc=19,38.635001,-121.328106&locations=[{"lat":38.634851483739276,"lon":-121.32811278104782},{"lat":38.635188807408504,"lon":-121.32810473442078}]&costing="auto"`
screenshot from 2018-06-13 11-04-44

* Wrong `demos/routing/index-internal.html#loc=19,38.634781,-121.328275&locations=[{"lat":38.63524956740381,"lon":-121.32812619209288},{"lat":38.634870340383785,"lon":-121.32812082767487}]&costing="auto"`
screenshot from 2018-06-13 11-06-49

* Correct if the target node moved to other edge  `demos/routing/index-internal.html#loc=19,38.634781,-121.328275&locations=[{"lat":38.63524956740381,"lon":-121.32812619209288},{"lat":38.634870340383785,"lon":-121.32812082767487}]&costing="auto"`
screenshot from 2018-06-13 11-08-14

### PR DESCRIPTION
**Pull request by dnesbitt61**
The EdgeStatus refactor caused an issue where previously the origin edges for A* where not labeled so that the edge could be properly visited later if used as a destination. Added some trivial_path tests using auto costing (prior test used pedestrian so they didn't catch this) with the static Utrecht data.

fixes #1359 

 - [x] Add tests
 - [x] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses

### CODE REVIEW

File: test/trivial_paths.cc [hunk 1]
```diff
@@ -115,8 +114,10 @@ const auto config = json_to_pt(R"({
 
 } // namespace
 
-
-void try_path(GraphReader& reader, loki_worker_t& loki_worker, const char* test_request, const uint32_t expected_edgecount) {
+void try_path(GraphReader& reader,
+              loki_worker_t& loki_worker,
+              const char* test_request,
+              const uint32_t expected_edgecount) {
```
Comment (kevinkreiser) [inline test/trivial_paths.cc]: these look like whitespace changes! has the formatter changed again?
