### PR TITLE
fix tile naming to be robust to all kinds of stuff. fixes #651

### LINKED ISSUE #651: tile paths should be robust to other numbers in them
back when we added tar extracts we simplified the way we read a file name into a tile_id. we took some shortcuts that ended up meaning that having a directory structure that has numbers in it other than those belonging to the tile_id would result in the wrong tile_id values coming out. we'll fix it by just only considering numbers, slashes and the extension of the file from the right.

### PR DESCRIPTION
**Pull request by kevinkreiser**
added lots of tests
made it so we can actually support numbers in the parts of the path that arent the tiles themselves
lots of other tests in there to reject stuff that almost looks like valid tiles names but arent

### CODE REVIEW

File: src/baldr/tilehierarchy.cc [hunk 1]
```diff
@@ -16,6 +16,10 @@ std::map<uint8_t, TileLevel> TileHierarchy::levels_  = {
     midgard::Tiles<midgard::PointLL>{{{-180, -90}, {180, 90}}, 4, static_cast<unsigned short>(kBinsDim)}}}
 };
 
+//Should we make a class lower than service other for transit?
+TileLevel TileHierarchy::transit_level_ = {2, stringToRoadClass.find("ServiceOther")->second, "transit",
```
Comment (kevinkreiser) [inline src/baldr/tilehierarchy.cc]: we may want to add this to other functions that get access to the levels but need to be careful of side effects due to transit being a special level

**Comment by dnesbitt61** [comment]
:shipit:
