### PR TITLE
Clamp grades on bridges and tunnels

### LINKED ISSUE #5708: Consecutive tunnels/bridges have bad elevation and weighted grade
I noted that an incorrect node in the center of the Borden Tunnel along the Greater Alleghany Passage (just north of Frostburg, MD) caused detours that avoided one tunnel edge and reconnected in the middle of the tunnel (impossible!). Now this node has been removed so there is now just one tunnel edge. However, this problem occurs other places where adjacent bridge/tunnel edges occur. (I looked for places where weigted_grade == 15 and the edge is a bridge or a tunnel - there were plenty!). In these places, the elevation is incorrect and weighted grade can be extreme - due to one end being at ground level when entering the tunnel and the other end being on the terrain above the tunnel.

In tyr/serializers we "fix" elevation along consecutive bridge/tunnel edges so that the elevation returned avoids the spikes and dips that can occur on bridges/tunnels. Due to this it is perhaps not necessary to "fix" the edge elevation stored in EdgeInfo for these cases. It could be somewhat complicated to look at adjacent edges and apply fixes - since elevationbuilder works on a single edge at a time.

However, we should address weighted_grade on bridge/tunnel edges so we avoid the extremes that can occur. I propose simply clamping weighted grade to "reasonable" values for tunnels/bridges. Perhaps anything < 4 is assigned 4, and anything > 8 is assigned 8. (I think 6 is the weighted grade that indicates mostly flat elevation along an edge). This should fix issues where "detours" occur to avoid incorrect extreme grades.

### PR DESCRIPTION
**Pull request by dnesbitt61**
Clamp grades and weighted grades to +/- 3% on bridges and tunnels. Thispatches a bug where elevation is not corrected properly in elevation builder on consecutive connected bridges/tunnels. Since we "fix" the elevation returned along routes for these cases, this patch should fix cases where routes detour around these bridge/tunnel cases due to extreme weighted grade.

# Issue

fixes #5708 

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too
 - [ ] If you made changes to a translation file, [update transifex](docs/docs/locales.md) too

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

File: src/mjolnir/elevationbuilder.cc [hunk 1]
```diff
@@ -229,10 +229,24 @@ void add_elevations_to_single_tile(GraphReader& graphreader,
...
+    // but weighted grade can cause route issues.
+    if (directededge.bridge() || directededge.tunnel()) {
+      // Clamp grades to +/- 3% (weighted grade values between 4 and 8)
+      weighted_grade = std::clamp(weighted_grade, 4u, 8u);
+      if (max_up_slope > 3.0f) {
+        max_up_slope = 3.0f;
+      }
+      if (max_down_slope < -3.0f) {
+        max_down_slope = -3.0f;
+      }
```
Comment (kevinkreiser) [inline src/mjolnir/elevationbuilder.cc]: nit:
```suggestion
      max_up_slope = std::min(3.0f, max_up_slope);
      max_down_slope = std::max(-3.0f, max_down_slope);
```

**Review by kevinkreiser — DISMISSED** [review]
while im certain there are tunnels/bridges who are steeper than +-3%, we cant know what they really are so this seems reasonable to me!

**Comment by dnesbitt61** [comment]
We don't really know the elevation along bridges or tunnels. Just trying to prevent extreme weighted grades due to reading elevation "above" a tunnel or "below" a bridge.

**Comment by dnesbitt61** [comment]
Elevation builder "corrects" elevation on single bridge/tunnel edges by looking up elevation at each end and doing a linear interpolation between the 2 ends. This, of course, makes the bridge "flat" but removes the issue of elevation falling to the water below a bridge or rising to the hill above the tunnel (both of which are usually worse than incorrectly making the bridge/tunnel flat).
Elevation along a route is "corrected" in serializers.h for cases of consecutive bridges and tunnels - again by linear interpolation between the elevation at the beginning and end of the sequence of bridge/tunnel edges.
The only way I can think to find the true elevation along bridges/tunnels is by using actual ride data taken with accurate elevation sensors (e.g. bicycle computers with barometric pressure sensors for elevation).
