### PR TITLE
Set side of street for trace route

### LINKED ISSUE #1719: Missing the destination side of street for OSRM compatibility mode
## Issue
While testing shared guidance with trace route, discovered that the side of street is missing for the destination maneuver when using the OSRM compatibility mode.
Tried sending locations with the trace_route call but that did not work.

## Task

- [ ] Update logic to add in the destination side of street when needed
- [ ] Test

### PR DESCRIPTION
**Pull request by dnesbitt61**
When 2 locations are provided in addition to the shape/GPS trace.
fixes #1719 

## Tasklist

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

### CODE REVIEW

File: src/loki/trace_route_action.cc [hunk 1]
```diff
@@ -171,12 +171,78 @@ void loki_worker_t::locations_from_shape(valhalla_request_t& request) {
...
+    // Project first and last shape point onto nearest edge(s). Clear current locations list
+    // and set the path locations
     auto projections = loki::Search(locations, *reader, edge_filter, node_filter);
     request.options.clear_locations();
     PathLocation::toPBF(projections.at(locations.front()), request.options.mutable_locations()->Add(),
                         *reader);
     PathLocation::toPBF(projections.at(locations.back()), request.options.mutable_locations()->Add(),
                         *reader);
+
+    // If locations were provided, backfill the origin and dest lat,lon and update
```
Comment (kevinkreiser) [inline src/loki/trace_route_action.cc]: why don't the `projections` above already have this information? why would we need to recompute it?

Comment (dnesbitt61) [reply src/loki/trace_route_action.cc]: if this is the trace from a prior route then the first and last points are on the edge so no side of street is provided. This allows an origin and a destination location to be passed in for these cases so a side of street can be determined. Code above basically clears out locations and uses the first and last shape point as inputs to Search.

Comment (kevinkreiser) [reply src/loki/trace_route_action.cc]: could we expose this function: https://github.com/valhalla/valhalla/blob/master/src/loki/search.cc#L89-L104

or something and call it from both search.cc and here so that we are both not duplicated the logic and making sure we have consistent behavior? maybe we could even move it to a util function in `baldr`?

Comment (dgearhart) [reply src/loki/trace_route_action.cc]: @dnesbitt61 were you going to try to reuse existing search logic?

Comment (dnesbitt61) [reply src/loki/trace_route_action.cc]: this is a member of candidate_t - which I don't think is readily available from the PathLocations or pbf. Also, the "duplicated code" is setting the pbf values directly, rather than the PathLocation members, so new code would still be needed to put these in the pbf.

Comment (kevinkreiser) [reply src/loki/trace_route_action.cc]: i was suggesting pulling that method out of `candidate_t` and just making it a stand along thing for computing the side of street given some inputs. this would also make sure that its actually tested since the code added in this PR is not.

Comment (kevinkreiser) [reply src/loki/trace_route_action.cc]: dont let me block this PR, we can just add a `TODO` in here tthat says something vague about sharing this logic with the stuff in search.cc in the future if that suits you for now?

Comment (dnesbitt61) [reply src/loki/trace_route_action.cc]: I added a TODO in code so we can consider changing this in the future.

**Comment by dnesbitt61** [comment]
I fixed an issue computing the destination side of street and now the test cases pass.
