### PR TITLE
bug fix for mapmatch shape and duration

### LINKED ISSUE #2086: Map Matching Shape Bug
This request has an issue with the geometry of the first leg:

{"shape":[
{"lat": 39.600269, "lon": -76.110611, "time": 0.000000},
{"lat": 39.600029, "lon": -76.110329, "time": 12.988904},
{"lat": 39.599590, "lon": -76.109787, "time": 37.253273},
{"lat": 39.599430, "lon": -76.109596, "time": 45.965481},
{"lat": 39.599361, "lon": -76.109428, "time": 52.013008},
{"lat": 39.599331, "lon": -76.109306, "time": 55.975593},
{"lat": 39.599339, "lon": -76.109169, "time": 60.264475},
{"lat": 39.599331, "lon": -76.109306, "time": 64.553356},
{"lat": 39.599361, "lon": -76.109428, "time": 68.515941},
{"lat": 39.599388, "lon": -76.109543, "time": 72.208026},
{"lat": 39.599590, "lon": -76.109787, "time": 83.275676},
{"lat": 39.599911, "lon": -76.110191, "time": 101.185228}
],"shape_match":"map_snap", "costing":"bicycle", "format": "osrm", "shape_format": "polyline5"}

There is a disconnect at the turnaround point (where the road changes from South Main Street to Bainbridge Road near the bend in the center of this map):
https://www.openstreetmap.org/search?query=39.599430%2C-76.109596#map=19/39.59946/-76.10923
The last edge of the first route in the result does not follow the shape of the edge, rather it connects in a straight line from the last node (where the entrance to the parking area is) to the turnaround point.

image

### PR DESCRIPTION
**Pull request by yuzheyan**
# Issue
The mapmatching logic has flaws in handling matching results that lands on intersections. There are usually several edges that starts/ends at the intersection, however, the matching results returns less edge candidate for the location than it should, thus, sometimes, the edge results that the location holds can not match edges in previous/next states. When logic tries to recover the tour from edge the matching results, it assumes consistancy in edges among states. This is where the bug occurs.    
Screen Shot 2019-12-16 at 4 35 23 PM
Screen Shot 2019-12-16 at 4 36 55 PM
Screen Shot 2019-12-16 at 4 37 55 PM

fixes #2086

### CODE REVIEW

File: src/meili/map_matcher.cc [hunk 1]
```diff
@@ -235,10 +235,10 @@ MatchResult FindMatchResult(const MapMatcher& mapmatcher,
   }
 
   // If we failed to get a valid edge or can't find it
-  // At least we know which point it matches
+  // At least we know which point it matches, to make leg builder
+  // work properly we snap the node at the end of the previous state
   const auto& edge = state.candidate().edges.front();
-  return {edge.projected,     std::sqrt(edge.distance), edgeid,
-          edge.percent_along, measurement.epoch_time(), stateid};
+  return {edge.projected, std::sqrt(edge.distance), edgeid, 1.0, measurement.epoch_time(), stateid};
```
Comment (yuzheyan) [inline src/meili/map_matcher.cc]: by changing the edge.percent_along (0.0) in old logic to 1.0. The match result returned will be put on the edge of the last edge of the previous state.

An alternative fix could be:
return {edge.projected, std::sqrt(edge.distance), edge.id, edge.percent_along, measurement.epoch_time(), stateid};
However, by doing so, we break the unit tests in trace attributes. Since this will generate empty path edges from meili mapmatching return. We currently do not handle such cases.

**Comment by kevinkreiser** [comment]
we should investiage a little bit more what is causing this. why doesnt it find the ending edge id in the candidate edges list in the first place? specifically for the example image that @dnesbitt61 shared, what is going on? the match in that case looks very simple so before we fix it by hardcoding the percentage along we should probably figure out why its happening.

based on the imagery i think what is happening is the following:

     E1       X2       E2
------------>N1------------->N2
    X1

you have edge 1 ending at node 1 pointing to edge 2 ending at node 2. the candidates for match point X2 are all the edges at node 1. in other words the input location is closest to the node 1. this means that both the end of edge 1 and the beginning of edge 2 are valid and basically equivalent candidates. for whatever reason it picks edge 1 at 100% along for the route ending at X2 and for the route beginning at X2 it picks edge 2 at 0% along.

i think the correct thing to do here would be to detect that and fix the states so that they agree on which candidate they are to use. looking up a few lines i see that it forces the start of the next route chunk to start where the last one left off (or that same idea but in reverse order). i expect that this is why the edge ids dont match. one left off at e1(100%) and the other starts at e2(0%). the code doesnt realize that these two things are really the same.

one thing we could do is when we choose candidates we dont allow ambiguities an internal match points. so in the code that calls AppendMeasurement we could change it to detect when the closest thing is the node and only put one of the edge candidates in there. we would have to disable this on the first and last input points but any intermediate ones could have this "deduplication" applied to them.

File: src/meili/candidate_search.cc [hunk 2]
```diff
@@ -109,7 +109,10 @@ CandidateQuery::WithinSquaredDistance(const midgard::PointLL& location,
 
     if (correlated.edges.size()) {
       // Add back if it is an edge correlated or it's a node correlated
-      // but it's not added yet
+      // but it's not added yet. By only allow one snapped_node per intersection match
```
Comment (yuzheyan) [inline src/meili/candidate_search.cc]: This is where the intersection mismatching starts. The alternative fix here is to remove the condition . Instead of only allowing one snapped_node (one edge candidate for the intersection), we add all of edges ends/starts on that node to the candidates. And later, the use an exclusive search from the previous state and the next state to match edge transition consistency.

Comment (kevinkreiser) [reply src/meili/candidate_search.cc]: This is the important part which as two competing ideas going on. That `|| visited_nodes.insert(snapped_node).second` will exclude certain edge candidates at the node (randomly, first one wins). Lets take the following example:

```
         0
         ||
       C || D
         ||
         ||
   A     ||     E
======== 1 ======== 2
   B     ||     F
         ||
         ||
       G || H
         ||
```

The input locations are labled `0` through `2`, the edges are labeled `A` through `H`. Imagine that input point `1` is at the node where all the edges cross. But the candidate_search encounters edges `A` and `B` first. What on earth can the map matching be? If edges `A` `C` `E` and `H` end at the node at `1`, then you'd get something like: `C.0->A.1->F.1`. However `C` does not connect to `A` so what do we have, a discontinuity?

The problem here is we want to minimize the number of candidates that we have in any given state of the HMM because it exploses the permutations we have to evaluate. To the router though `A.1` is just as good as `F.0`. That is why this `if` check excludes adding more candidates.
