### PR TITLE
Fixed fork assignments and on ramps for OSRM compatibility mode

### LINKED ISSUE #140: Review "keep straight" logic
(2016-03-17T14:25:05Z) @dgearhart : originally created valhalla/odin#249

Should this example be keep right?
j '{"locations":[{"lat":40.377975,"lon":-76.667252,"street":"I 81 North"},{"lat":40.378349,"lon":-76.657860,"street":"Bow Creek Road"}],"costing":"auto","directions_options":{"units":"kilometers"}}' --config ../conf/valhalla.json
screenshot from 2016-03-17 10 24 48

### LINKED ISSUE #703: Do not call out fork at bidirectional ramp
Update ramp logic so we do not call out a maneuver when transitioning from a one way ramp to a bidirectional ramp and the reverse case too
Test case 1:
https://github.com/valhalla/valhalla/blob/master/test_requests/pa_interchange_routes.txt#L55
Remove maneuver 3
screenshot from 2017-05-08 09-54-56

Test case 2:
https://github.com/valhalla/valhalla/blob/master/test_requests/pa_interchange_routes.txt#L59
Remove maneuver 3
screenshot from 2017-05-08 09-57-18

### LINKED ISSUE #1733: Update the Valhalla OSRM compatibility to set the proper turn type onto ramp
## Issue
Currently, the assignment of the Valhalla OSRM compatibility attributes are interpreted as a `Take the ramp on the left` instead of a `Turn left to take the ramp`

#### Step 2
Shared guidance should be `Turn left…` like both standard guidance and Valhalla

## Tasks

- [x] Analyze and update logic
- [x] Test

### PR DESCRIPTION
**Pull request by dgearhart**
# Issue

Update fork assignment to call out right/left at bifurcation. Fixes #140
Update ramp logic so we do not call out a maneuver when transitioning from a one way ramp to a bidirectional ramp and the reverse case too. Fixes #703
Update `on ramp` assignment to call out turn vs. take. Fixes #1733 

### Example 1
image
``` diff
< BEFORE
< 3: Keep straight to take PA 743 South toward Elizabethtown.
> AFTER
> 3: Keep right to take PA 743 South toward Elizabethtown.
```

### Example 2
image
``` diff
< BEFORE
< 2: Take exit 24 on the right onto PA 238 toward Emigsville.
< 3: Keep straight toward Emigsville.
< 4: Turn right onto Church Road/PA 238.
> AFTER
> 2: Take exit 24 on the right onto PA 238 toward Emigsville.
> 3: Turn right onto Church Road/PA 238.
```

### Example 3
image
Standard guidance and shared guidance are now the same
image

## Tasklist

 - [x] Test
 - [x] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

File: src/odin/enhancedtrippath.cc [hunk 1]
```diff
@@ -1110,6 +1110,19 @@ uint32_t EnhancedTripPath_Node::GetStraightestTraversableIntersectingEdgeTurnDeg
   return staightest_turn_degree;
 }
 
+bool EnhancedTripPath_Node::IsStraightestTraversableIntersectingEdgeReversed(
+    uint32_t from_heading,
+    const TripPath_TravelMode travel_mode) {
+  uint32_t straightest_traversable_xedge_turn_degree =
+      GetStraightestTraversableIntersectingEdgeTurnDegree(from_heading, travel_mode);
+  // Determine if the straightest intersecting edge is in the reversed direction
+  if ((straightest_traversable_xedge_turn_degree > 124) &&
```
Comment (dnesbitt61) [inline src/odin/enhancedtrippath.cc]: magic numbers...perhaps a constexpr

File: src/odin/maneuversbuilder.cc [hunk 2]
```diff
@@ -1697,11 +1697,14 @@ bool ManeuversBuilder::IsFork(int node_index,
...
     // if there is a similar traversable intersecting edge
     //   or there is a traversable intersecting edge and curr edge is link(ramp)
+    //   and the straightest intersecting edge is not in the reversed direction
     if (((xedge_counts.left_similar_traversable_outbound > 0) ||
          (xedge_counts.right_similar_traversable_outbound > 0)) ||
         (((xedge_counts.left_traversable_outbound > 0) ||
           (xedge_counts.right_traversable_outbound > 0)) &&
-         curr_edge->IsRampUse())) {
+         curr_edge->IsRampUse() &&
+         !node->IsStraightestTraversableIntersectingEdgeReversed(prev_edge->end_heading(),
```
Comment (dnesbitt61) [inline src/odin/maneuversbuilder.cc]: wow - that is one long (but descriptive) function name

File: src/odin/enhancedtrippath.cc (hunk 1 above)
Comment (dgearhart) [reply src/odin/enhancedtrippath.cc]: agreed - I created an issue to fix all turn degree magic numbers https://github.com/valhalla/valhalla/issues/1739
