### PR TITLE
Additional Fixed Speed Costing Option

### LINKED ISSUE #3504: Isochrone calculations: use fixed vehicle speed?
Is there an easy way via costing options or other request options or some underlying service configuration to use the pedestrian/bicycle/vehicle's current known speed as the speed used in calculations rather than whatever gets derived from each OSM road segment?  I'm basically looking for a simple/more naive approach that assumes the vehicle is traveling at whatever speed it's currently traveling at independent of speed limits/assumptions about the road segments in question. The goal is to provide a near real-time measure of where a vehicle might be in the next few minutes if it continues to travel at its current rate.

### PR DESCRIPTION
**Pull request by jbartrug**
# Issue

#fixes #3504. Adds in the option to use a fixed speed parameter to override the calculated speed for truck, auto, and motorcycle. Went with the option to add a custom costing option. Unit test written and also tested with the command line. 

## Tasklist

 - [x] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

No requirements or relations.

### CODE REVIEW

File: src/sif/autocost.cc [hunk 1]
```diff
@@ -80,6 +80,8 @@ constexpr ranged_default_t<float> kUseDistanceRange{0, kDefaultUseDistance, 1.0f
 constexpr ranged_default_t<float> kAutoHeightRange{0, kDefaultAutoHeight, 10.0f};
 constexpr ranged_default_t<float> kAutoWidthRange{0, kDefaultAutoWidth, 10.0f};
 constexpr ranged_default_t<uint32_t> kProbabilityRange{0, kDefaultRestrictionProbability, 100};
+constexpr ranged_default_t<uint32_t> kFixedSpeedRange{0, 0, baldr::kMaxSpeedKph};
```
Comment (nilsnolde) [inline src/sif/autocost.cc:83]: overall I think you should move the whole logic into the parent class in `sif/dynamiccost`, similar to how it's done for `top_speed`. that'll remove a lot of redundant code. e.g. move this line here to `dynamiccost.cc:108`. I'll give some tips where to move the other parts as well.

File: src/sif/autocost.cc [hunk 2]
```diff
@@ -340,6 +342,7 @@ class AutoCost : public DynamicCost {
   // Vehicle attributes (used for special restrictions and costing)
   float height_; // Vehicle height in meters
   float width_;  // Vehicle width in meters
+  float fixed_speed_;
```
Comment (nilsnolde) [inline src/sif/autocost.cc:345]: this goes to dynamiccost.h:961 or so

File: src/sif/autocost.cc [hunk 3]
```diff
@@ -409,6 +412,7 @@ AutoCost::AutoCost(const Costing& costing, uint32_t access_mask)
   // Get the vehicle attributes
   height_ = costing_options.height();
   width_ = costing_options.width();
+  fixed_speed_ = costing_options.fixed_speed();
```
Comment (nilsnolde) [inline src/sif/autocost.cc:415]: this to dynamiccost.h.get_base_costs():1060

File: src/sif/autocost.cc [hunk 4]
```diff
@@ -708,6 +717,8 @@ void ParseAutoCostOptions(const rapidjson::Document& doc,
   JSON_PBF_DEFAULT(co, false, json, "/include_hot", include_hot);
   JSON_PBF_DEFAULT(co, false, json, "/include_hov2", include_hov2);
   JSON_PBF_DEFAULT(co, false, json, "/include_hov3", include_hov3);
+  JSON_PBF_RANGED_DEFAULT(co, kFixedSpeedRange, json, "/fixed_speed", fixed_speed);
```
Comment (nilsnolde) [inline src/sif/autocost.cc:720]: redundant as you already set that in the parent class. actually you can remove the 3 lines above as well, they're redundant too

File: src/sif/dynamiccost.cc [hunk 5]
```diff
@@ -105,6 +105,7 @@ constexpr ranged_default_t<float> kClosureFactorRange{1.0f, kDefaultClosureFacto
 
 constexpr ranged_default_t<uint32_t> kVehicleSpeedRange{10, baldr::kMaxAssumedSpeed,
                                                         baldr::kMaxSpeedKph};
+constexpr ranged_default_t<uint32_t> kFixedSpeedRange{0, 0, baldr::kMaxSpeedKph};
```
Comment (nilsnolde) [inline src/sif/dynamiccost.cc:108]: ah you already put it here.. 

hm, not so sure if 0 is a good default, I'll let others comment on that

File: src/sif/motorcyclecost.cc [hunk 6]
```diff
@@ -54,6 +54,7 @@ constexpr float kLeftSideTurnCosts[] = {kTCStraight,         kTCSlight,  kTCUnfa
 constexpr ranged_default_t<float> kUseHighwaysRange{0, kDefaultUseHighways, 1.0f};
 constexpr ranged_default_t<float> kUseTollsRange{0, kDefaultUseTolls, 1.0f};
 constexpr ranged_default_t<float> kUseTrailsRange{0, kDefaultUseTrails, 1.0f};
+constexpr ranged_default_t<uint32_t> kFixedSpeedRange{0, 0, baldr::kMaxSpeedKph};
```
Comment (nilsnolde) [inline src/sif/motorcyclecost.cc:57]: redundant

File: src/sif/motorcyclecost.cc [hunk 7]
```diff
@@ -272,6 +273,7 @@ class MotorcycleCost : public DynamicCost {
   float toll_factor_;        // Factor applied when road has a toll
   float surface_factor_;     // How much the surface factors are applied when using trails
   float highway_factor_;     // Factor applied when road is a motorway or trunk
+  float fixed_speed_;
```
Comment (nilsnolde) [inline src/sif/motorcyclecost.cc:276]: redundant

File: src/sif/motorcyclecost.cc [hunk 8]
```diff
@@ -291,6 +293,8 @@ MotorcycleCost::MotorcycleCost(const Costing& costing)
   // Get the base costs
   get_base_costs(costing);
 
+  fixed_speed_ = costing_options.fixed_speed();
```
Comment (nilsnolde) [inline src/sif/motorcyclecost.cc:296]: redundant

File: src/sif/truckcost.cc [hunk 9]
```diff
@@ -72,6 +72,7 @@ constexpr ranged_default_t<float> kTruckHeightRange{0, kDefaultTruckHeight, 10.0
 constexpr ranged_default_t<float> kTruckWidthRange{0, kDefaultTruckWidth, 10.0f};
 constexpr ranged_default_t<float> kTruckLengthRange{0, kDefaultTruckLength, 50.0f};
 constexpr ranged_default_t<float> kUseTollsRange{0, kDefaultUseTolls, 1.0f};
+constexpr ranged_default_t<uint32_t> kFixedSpeedRange{0, 0, baldr::kMaxSpeedKph};
```
Comment (nilsnolde) [inline src/sif/truckcost.cc:75]: redundant

File: src/sif/truckcost.cc [hunk 10]
```diff
@@ -276,6 +277,7 @@ class TruckCost : public DynamicCost {
   float height_;    // Vehicle height in meters
   float width_;     // Vehicle width in meters
   float length_;    // Vehicle length in meters
+  float fixed_speed_; // Vehicle speed in kmph
```
Comment (nilsnolde) [inline src/sif/truckcost.cc:280]: redundant

File: src/sif/truckcost.cc [hunk 11]
```diff
@@ -302,6 +304,7 @@ TruckCost::TruckCost(const Costing& costing)
   height_ = costing_options.height();
   width_ = costing_options.width();
   length_ = costing_options.length();
+  fixed_speed_ = costing_options.fixed_speed();
```
Comment (nilsnolde) [inline src/sif/truckcost.cc:307]: redundant

File: src/sif/truckcost.cc [hunk 12]
```diff
@@ -634,6 +646,8 @@ void ParseTruckCostOptions(const rapidjson::Document& doc,
   JSON_PBF_RANGED_DEFAULT(co, kTruckWidthRange, json, "/width", width);
   JSON_PBF_RANGED_DEFAULT(co, kTruckLengthRange, json, "/length", length);
   JSON_PBF_RANGED_DEFAULT(co, kUseTollsRange, json, "/use_tolls", use_tolls);
+  JSON_PBF_RANGED_DEFAULT(co, kFixedSpeedRange, json, "/fixed_speed", fixed_speed);
```
Comment (nilsnolde) [inline src/sif/truckcost.cc:649]: redundant

File: test/gurka/test_fixed_speed.cc [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+TEST_F(FixedSpeedTest, ClampMaxSpeed) {
+  Options options;
+  rapidjson::Document dom;
+  rapidjson::SetValueByPointer(dom, "/fixed_speed", 500);
+
+  options.set_costing_type(Costing::auto_);
+  auto& co = (*options.mutable_costings())[Costing::auto_];
+  sif::ParseBaseCostOptions(*rapidjson::GetValueByPointer(dom, ""), &co, {});
+
+  ASSERT_EQ(co.options().top_speed(), baldr::kMaxAssumedSpeed);
```
Comment (nilsnolde) [inline test/gurka/test_fixed_speed.cc:77]: copy/paste fail?

File: src/sif/truckcost.cc [hunk 14]
```diff
@@ -607,6 +616,9 @@ Cost TruckCost::TransitionCostReverse(const uint32_t idx,
 // assume the maximum speed is used to the destination such that the time
 // estimate is less than the least possible time along roads.
 float TruckCost::AStarCostFactor() const {
+  if(fixed_speed_ != 0){
+    return speedfactor_[fixed_speed_];
+  }
```
Comment (nilsnolde) [inline src/sif/truckcost.cc:621]: makes sense to me. shouldn't we do that to the other costing models too?

File: src/sif/motorcyclecost.cc [hunk 15]
```diff
@@ -579,6 +588,8 @@ void ParseMotorcycleCostOptions(const rapidjson::Document& doc,
   JSON_PBF_RANGED_DEFAULT(co, kUseHighwaysRange, json, "/use_highways", use_highways);
   JSON_PBF_RANGED_DEFAULT(co, kUseTollsRange, json, "/use_tolls", use_tolls);
   JSON_PBF_RANGED_DEFAULT(co, kUseTrailsRange, json, "/use_trails", use_trails);
+  JSON_PBF_RANGED_DEFAULT(co, kFixedSpeedRange, json, "/fixed_speed", fixed_speed);
```
Comment (nilsnolde) [inline src/sif/motorcyclecost.cc:591]: redundant

**Review by nilsnolde — CHANGES_REQUESTED** [review]
looks good generally, thanks! you put in a few too many things, sorry for all the "redundant" comments, also check them again for consistency, might be I put one too many or missed one. basically everything can happen in the dynamiccost parent class and you just access `fixed_speed_` in the derived costing classes to set astar heuristic and edge cost.

I'd also wait for @kevinkreiser 's review (or someone else's). `quite sure this is the way to go, but maybe not. decreases the chance that you'd have to refactor again;)

**Comment by nilsnolde** [comment]
what you can already do: run `./scripts/format.sh` locally and commit the changes it does. I can recommend adding it as a git commit hook:
```
cat ./scripts/format.sh > .git/hooks/pre-commit && tail -n +7 scripts/error_on_dirty.sh >> .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
```

File: src/sif/autocost.cc (hunk 1 above)
Comment (nilsnolde) [reply src/sif/autocost.cc:83]: think you already did that after reviewing everything. so you mostly need to remove some stuff

**Comment by kevinkreiser** [comment]
i agree with @nilsnolde we should do this in the base class and access it from all the other classes. this does bring up the question about bikes and pedestrians though and how they already have speeds that you can specify. we can rectify that later though

File: src/sif/dynamiccost.cc (hunk 5 above)
Comment (jbartrug) [reply src/sif/dynamiccost.cc]: Thanks for all the feedback! I really appreciate it. Just wanted to explain the reasoning for 0 as a default. My thinking was I needed a value that was outside the range of viable numbers, so that there wouldn't be any limitations on what fixed speed you could set.  Zero made sense because if the fixed speed  is zero then you don't need any fixed speed routing you're at a standstill, you should use the estimated speed instead. Totally open to other options that was just my base reasoning.

File: proto/options.proto [hunk 16]
```diff
@@ -307,6 +307,9 @@ message Costing {
     oneof has_elevator_penalty {
       float elevator_penalty = 79;
     }
+    oneof has_fixed_speed {
+      float fixed_speed = 80;
+    }
```
Comment (kevinkreiser) [inline proto/options.proto:312]: since you use a default of `0` you can simply make this:

```suggestion
    float fixed_speed = 80;
```

File: src/sif/autocost.cc [hunk 17]
```diff
@@ -275,6 +275,9 @@ class AutoCost : public DynamicCost {
    * estimate is less than the least possible time along roads.
    */
   virtual float AStarCostFactor() const override {
+    if (fixed_speed_ != 0) {
+      return speedfactor_[fixed_speed_];
+    }
```
Comment (kevinkreiser) [inline src/sif/autocost.cc:280]: rather than adding this complexity perhaps we should solve the problem of when people are  setting both of these and choose a winner. and whichever the winner is we should assign to `topspeed_` and let this code unchanged.

intuitively, when someone specifies `fixed_speed` then `top_speed` should get assigned the same value. does that make sense?

File: src/sif/autocost.cc [hunk 18]
```diff
@@ -498,6 +501,11 @@ Cost AutoCost::EdgeCost(const baldr::DirectedEdge* edge,
   auto edge_speed = tile->GetSpeed(edge, flow_mask_, time_info.second_of_week, false, &flow_sources,
                                    time_info.seconds_from_now);
   auto final_speed = std::min(edge_speed, top_speed_);
+
+  if (fixed_speed_ != 0) {
+    final_speed = fixed_speed_;
+  }
+
```
Comment (kevinkreiser) [inline src/sif/autocost.cc:508]: in the case someone is using fixed speed its highly inefficient to still called `tile->GetSpeed()` just to throw the value away. maybe this would be better:

```suggestion
  auto edge_speed = fixed_speed_ != 0 ? tile->GetSpeed(edge, flow_mask_, time_info.second_of_week, false, 
                                   &flow_sources, time_info.seconds_from_now) : fixed_speed_;
  auto final_speed = std::min(edge_speed, top_speed_);
```

File: src/sif/dynamiccost.cc (hunk 5 above)
Comment (kevinkreiser) [reply src/sif/dynamiccost.cc]: i think this will work fine however i would suggest making `0` a named constant so the check in the actual costing will be more readible

Comment (kevinkreiser) [reply src/sif/dynamiccost.cc]: one thing that is a bit strange from the API perspective is that you can actually set it to 0. i suppose the docs sh ould say valid values are from 1 to 160kph or whatever so people dont have to worry about what meaning 0 would have

File: src/sif/autocost.cc (hunk 17 above)
Comment (kevinkreiser) [reply src/sif/autocost.cc:280]: I disagree. Fixed speed means only one speed. We want that disabled unless someone specified it.

Comment (nilsnolde) [reply src/sif/autocost.cc:280]: not sure what you disagree with haha I was just saying I agree with you, albeit not in a straight forward way

Comment (kevinkreiser) [reply src/sif/autocost.cc:280]: sorry i disagree that we should assign top_speed to fixed_speed. if we do that then when someone says top_speed = 45, then we'll have fixed_speed = 45 and then every edge will be 45. maybe i am misunderstanding what you are saying? my assumption was that if fixed_speed is set, ie not 0, then we will use fixed_speed for every edge. so setting it to top_speed when top_speed is passed in will essentially break the whole top_speed feature. what am i missing here? :smile:

Comment (kevinkreiser) [reply src/sif/autocost.cc:280]: ah maybe this is a language thing, let me write it in code, when i read what you said:

> assign top_speed to fixed_speed

my brain saw this code:

```c++
fixed_speed = top_speed;
```

Comment (nilsnolde) [reply src/sif/autocost.cc:280]: ah well yeah, I meant it the other way around :smile: `top_speed = fixed_speed` when both are passed

File: src/sif/dynamiccost.cc (hunk 5 above)
Comment (jbartrug) [reply src/sif/dynamiccost.cc]: Sounds good made it a named constant called kDefaultFixedSpeed

File: src/sif/autocost.cc (hunk 18 above)
Comment (jbartrug) [reply src/sif/autocost.cc]: Agreed much more efficient. Changed to save that calculation.

File: proto/options.proto (hunk 16 above)
Comment (jbartrug) [reply proto/options.proto:312]: When I changed to that format I got a compile error saying the member didn't exist in costing options so I left it as it was.

File: src/sif/autocost.cc (hunk 17 above)
Comment (nilsnolde) [reply src/sif/autocost.cc:280]: @jbartrug you can revert this change and rather do `top_speed = fixed_speed` if `fixed_speed != kDefaultFixedSpeed` in `dynamiccost.h::get_base_costs()`

File: src/sif/autocost.cc [hunk 19]
```diff
@@ -495,9 +498,13 @@ Cost AutoCost::EdgeCost(const baldr::DirectedEdge* edge,
                         const baldr::TimeInfo& time_info,
                         uint8_t& flow_sources) const {
   // either the computed edge speed or optional top_speed
-  auto edge_speed = tile->GetSpeed(edge, flow_mask_, time_info.second_of_week, false, &flow_sources,
-                                   time_info.seconds_from_now);
-  auto final_speed = std::min(edge_speed, top_speed_);
+  auto edge_speed = fixed_speed_ == 0
```
Comment (nilsnolde) [inline src/sif/autocost.cc:501]: should we use `kDefaultFixedSpeed` here as well?

Comment (nilsnolde) [reply src/sif/autocost.cc:501]: and all the other places I guess

File: test/gurka/test_fixed_speed.cc [hunk 20]
```diff
@@ -0,0 +1,78 @@
...
+  doTests("auto", {{"/costing_options/auto/fixed_speed", "50"}});
+}
+
+TEST_F(FixedSpeedTest, TruckFixedSpeed) {
+  doTests("truck", {{"/costing_options/truck/fixed_speed", "50"}});
+}
+
+TEST_F(FixedSpeedTest, MotorcycleFixedSpeed) {
+  doTests("motorcycle", {{"/costing_options/motorcycle/fixed_speed", "50"}});
+}
```
Comment (nilsnolde) [inline test/gurka/test_fixed_speed.cc:66]: would you mind adding a test covering the scenario where both `top_speed` and `fixed_speed` are specified?

File: valhalla/sif/dynamiccost.h [hunk 21]
```diff
@@ -1059,6 +1060,8 @@ class DynamicCost {
     flow_mask_ = costing_options.flow_mask();
     // Set the top speed a vehicle wants to go
     top_speed_ = costing_options.top_speed();
+    // Set the fixed speed a vehicle can go
+    fixed_speed_ = costing_options.fixed_speed();
```
Comment (nilsnolde) [inline valhalla/sif/dynamiccost.h:1064]:
```suggestion
    // Set the fixed speed a vehicle can go
    fixed_speed_ = costing_options.fixed_speed();
    top_speed_ = fixed_speed_ == kDefaultFixedSpeed ? costing_options.top_speed() : fixed_speed_;
```

File: src/sif/autocost.cc [hunk 22]
```diff
@@ -926,9 +933,11 @@ class TaxiCost : public AutoCost {
...
                         const baldr::TimeInfo& time_info,
                         uint8_t& flow_sources) const override {
-    auto edge_speed = tile->GetSpeed(edge, flow_mask_, time_info.second_of_week, false, &flow_sources,
-                                     time_info.seconds_from_now);
-    auto final_speed = std::min(edge_speed, top_speed_);
+    auto edge_speed = fixed_speed_ == 0
+                          ? tile->GetSpeed(edge, flow_mask_, time_info.second_of_week, false,
+                                           &flow_sources, time_info.seconds_from_now)
+                          : fixed_speed_;
+    auto final_speed = fixed_speed_ != 0 ? fixed_speed_ : std::min(edge_speed, top_speed_);
```
Comment (nilsnolde) [inline src/sif/autocost.cc:940]: edge_speed is already fixed_speed from above
```suggestion
    auto final_speed = std::min(edge_speed, top_speed_);
```

Comment (nilsnolde) [reply src/sif/autocost.cc:940]: same is in the other costing models

**Review by nilsnolde — CHANGES_REQUESTED** [review]
looks good so far @jbartrug thanks! just a couple of minor things, I think then it's good to :ship:

File: src/sif/autocost.cc (hunk 22 above)
Comment (nilsnolde) [reply src/sif/autocost.cc:940]: ah never mind this comment.. of course you want to fix the final speed.

File: test/gurka/test_fixed_speed.cc (hunk 20 above)
Comment (jbartrug) [reply test/gurka/test_fixed_speed.cc:66]: Sure thing, just added that test in the latest commit along with your other suggestions thanks.

**Review by nilsnolde — APPROVED** [review]
lgtm. let's wait for someone else to have to a look before merging.

**Comment by jbartrug** [comment]
@kevinkreiser Just wanted to check on the status of the review and merge of this MR. On my end it is ready to merge in but if there is anything else let me know what I can do.

File: valhalla/baldr/graphconstants.h [hunk 23]
```diff
@@ -103,6 +103,11 @@ constexpr uint32_t kMaxSpeedKph = std::max(kMaxTrafficSpeed, kMaxAssumedSpeed);
 // stretch, its unlikely to be good signal below this value
 constexpr uint32_t kMinSpeedKph = 5; // ~3 MPH
 
+// Default Fixed Speed. This is the default fixed speed that is assumed.
+// Unless otherwised specified no fixed speed will be assumed and speed will be
+// calculated from costing algorithm.
+constexpr uint32_t kDefaultFixedSpeed = 0; // ~0 MPH
```
Comment (kevinkreiser) [inline valhalla/baldr/graphconstants.h:109]: we should name this something more insightful. like `kDisableFixedSpeed`

File: docs/api/turn-by-turn/api-reference.md [hunk 24]
```diff
@@ -113,6 +113,7 @@ These options are available for `auto`, `bus`, and `truck` costing methods.
 | `country_crossing_penalty` | A penalty applied for a country crossing. This penalty can be used to create paths that avoid spanning country boundaries. The default penalty is 0. |
 | `shortest` | Changes the metric to quasi-shortest, i.e. purely distance-based costing. Note, this will disable all other costings & penalties. Also note, `shortest` will not disable hierarchy pruning, leading to potentially sub-optimal routes for some costing models. The default is `false`. |
 | `top_speed` | Top speed the vehicle can go. Also used to avoid roads with higher speeds than this value. `top_speed` must be between 10 and 252 KPH. The default value is 140 KPH. |
+| `fixed_speed` | Fixed speed the vehicle can go. Used to override the calculated speed. Can be useful if speed of vehicle is known. `fixed_speed` must be between 0 and 252 KPH. The default value is 0 KPH. If not set it will default to using the calculated speed based on the roadways. |
```
Comment (kevinkreiser) [inline docs/api/turn-by-turn/api-reference.md:116]:
```suggestion
| `fixed_speed` | Fixed speed the vehicle can go. Used to override the calculated speed. Can be useful if speed of vehicle is known. `fixed_speed` must be between 1 and 252 KPH. The default value is 0 KPH which disables fixed speed and falls back to the standard calculated speed based on the road attribution. |
```

File: proto/options.proto (hunk 16 above)
Comment (kevinkreiser) [reply proto/options.proto:312]: im sure we can fix that, we want to have as few `oneof`'s as possible. can you post back the compiler error?

**Comment by kevinkreiser** [comment]
@jbartrug i think you forgot motorscooter cost. i suspect we want this for all motorized costings

**Review by nilsnolde — DISMISSED** [review]
ready to merge I'd say:) sorry for the long wait @jbartrug

**Comment by jbartrug** [comment]
Thanks @nilsnolde would love to merge whenever. Although it looks like it has a linting stage error. It looks like the same error is present on master as well. I manually ran the linting locally and it didn't find anything.

**Comment by kevinkreiser** [comment]
Yeah it's not a linting error it's actually #3740

**Review by nilsnolde — DISMISSED** [review]

**Comment by nilsnolde** [comment]
hm, weird, it's failing the `fixed_speed` tests now.. will have a look later today, let's put it back in the queue for now

**Review by nilsnolde — APPROVED** [review]
this is done as well now

File: src/sif/dynamiccost.cc [hunk 25]
```diff
@@ -461,6 +463,9 @@ void ParseBaseCostOptions(const rapidjson::Value& json,
   JSON_PBF_DEFAULT(co, cfg.include_hot_, json, "/include_hot", include_hot);
   JSON_PBF_DEFAULT(co, cfg.include_hov2_, json, "/include_hov2", include_hov2);
   JSON_PBF_DEFAULT(co, cfg.include_hov3_, json, "/include_hov3", include_hov3);
+
+  co->set_fixed_speed(
+      kFixedSpeedRange(rapidjson::get<uint32_t>(json, "/fixed_speed", co->fixed_speed())));
```
Comment (nilsnolde) [inline src/sif/dynamiccost.cc:468]: old style parsing, because we opted not to make a `oneof` out of fixed_speed in the options.proto, since it defaults to 0 anyways.

**Review by kevinkreiser — APPROVED** [review]
