### PR TITLE
Fix avoid polygons again

### LINKED ISSUE #3182: Avoid polygons
The algorithm can't calculate a path, however when I take a polygon it can calculate the path here, everything normal if this polygon affected the path, I leave the example images here: 

Image with Polygons:
notwork

Image without Polygons:
work

And my request:

{
	"directions_type": "maneuvers",
	"avoid_polygons": [
		[
			[-8.899850490212819, 39.13892207569951],
			[-8.899855854630864, 39.13892415606849],
			[-8.899920227647314, 39.13891167385339],
			[-8.900242092729133, 39.14053226293175],
			[-8.900164308667662, 39.14054474485951],
			[-8.900000693917733, 39.139745897023865],
			[-8.899829032540767, 39.138930397175216],
			[-8.899850490212819, 39.13892207569951]
		],
		[
			[-8.90089085203469, 39.13890553686528],
			[-8.900890852034703, 39.138823362220464],
			[-8.901337439835736, 39.138843125751414],
			[-8.901637847245356, 39.13839480429094],
			[-8.90171026688879, 39.13841248755808],
			[-8.901405836165658, 39.13892113963512],
			[-8.900937790692456, 39.1389044966805],
			[-8.90089085203469, 39.13890553686528]
		]
	],
	"costing": "auto",
	"locations": [{
		"name": "startPlace",
		"lon": -9.1485128705079,
		"type": "break_through",
		"lat": 39.188744520260286
	}, {
		"min_road_class": "residential",
		"name": "firstStopPoint",
		"lon": -8.90767222222222,
		"type": "break",
		"lat": 39.1243722222222,
		"preferred_side": "opposite"
	}, {
		"name": "enPlace",
		"lon": -9.1485128705079,
		"type": "break_through",
		"lat": 39.188744520260286
	}],
	"language": "pt-PT",
	"costing_options": {
		"auto": {
			"service_penalty": 0,
			"use_highways": 1,
			"use_tolls": 1,
			"top_speed": 120,
			"use_tracks": 0,
			"use_living_streets": 0,
			"shortest": true
		}
	}
}

Is there any way to overcome this?
Thanks

### PR DESCRIPTION
**Pull request by nilsnolde**
Fixes #3182 

The issue was a little subtle: we register `std::vector<PointLL>` as a `bg::polygon` so the edge's `shape` was interpreted as a polygon geometry and then used to intersect with the avoid_polygons, which I guess is sorta undefined behavior (at least for me).

I also added a `to_geojson()` for debugging as you suggested @kevinkreiser, as a trace log, very helpful..

~~Could be done a bit different, by registering another structure with bg, e.g. `std::deque<PointLL>`, to avoid casting every edge to a linestring. With a few experiments I didn't see any significant performance deviation from master though, but let me know if you'd prefer that.~~ that only works if we register std::vector<PointLL> as linestring, of course bg::intersects needs two geometry types. For polygons we wouldn't need to register our own geometry type, we could use bg::model::polygon, but the Tiles::Intersect method somehow won't take that type as an argument.

### CODE REVIEW

File: src/loki/polygon_search.cc [hunk 1]
```diff
@@ -121,9 +158,11 @@ edges_in_rings(const google::protobuf::RepeatedPtrField<valhalla::Options_Ring>&
         // TODO: some logic to set percent_along for origin/destination edges
         // careful: polygon can intersect a single edge multiple times
         auto edge_info = tile->edgeinfo(edge);
+        // vector<PointLL> is reserved for bg as ring, need to cast to linestring
+        line_bg_t edge_line{edge_info.shape().begin(), edge_info.shape().end()};
         bool intersects = false;
         for (const auto& ring_loc : bin.second) {
-          intersects = bg::intersects(rings_bg[ring_loc], edge_info.shape());
+          intersects = bg::intersects(rings_bg[ring_loc], edge_line);
```
Comment (nilsnolde) [inline src/loki/polygon_search.cc:165]: that's the actual change

**Comment by nilsnolde** [comment]
@PureW maybe this also fixes the clang issues over at https://github.com/valhalla/valhalla/pull/2750#issuecomment-871672316 ?

File: src/loki/polygon_search.cc [hunk 2]
```diff
@@ -41,16 +37,10 @@ ring_bg_t PBFToRing(const valhalla::Options::Ring& ring_pbf) {
   for (const auto& coord : ring_pbf.coords()) {
     new_ring.push_back({coord.lng(), coord.lat()});
   }
+  bg::correct(new_ring);
```
Comment (kevinkreiser) [inline src/loki/polygon_search.cc:40]: whats that do? fix winding or self intersection?

File: src/loki/polygon_search.cc [hunk 3]
```diff
@@ -101,7 +91,7 @@ edges_in_rings(const google::protobuf::RepeatedPtrField<valhalla::Options_Ring>&
   for (const auto& ring_pbf : rings_pbf) {
     rings_bg.push_back(PBFToRing(ring_pbf));
     const ring_bg_t ring_bg = rings_bg.back();
-    rings_length += GetRingLength(ring_bg);
+    rings_length += bg::perimeter(ring_bg);
```
Comment (kevinkreiser) [inline src/loki/polygon_search.cc:94]: how does this know to use spherical coordinates and to return meters?

Comment (kevinkreiser) [reply src/loki/polygon_search.cc:94]: oh probably because of `geographic`?

File: src/loki/polygon_search.cc [hunk 4]
```diff
@@ -123,7 +150,8 @@ edges_in_rings(const google::protobuf::RepeatedPtrField<valhalla::Options_Ring>&
         auto edge_info = tile->edgeinfo(edge);
         bool intersects = false;
         for (const auto& ring_loc : bin.second) {
-          intersects = bg::intersects(rings_bg[ring_loc], edge_info.shape());
+          intersects = bg::intersects(rings_bg[ring_loc],
+                                      line_bg_t(edge_info.shape().begin(), edge_info.shape().end()));
```
Comment (kevinkreiser) [inline src/loki/polygon_search.cc:154]: > avoid_polygons intersected edges as polygons instead of linestrings

so previously it was treating the edge shape as a polygon rather than a line? treating it as a line should be slightly cheaper but i dont understand how that would make the difference for having an intersection and not. maybe it has to do with those edge shapes making self intersecting rings and the self intersecting parts not counting for intersection?

**Comment by PureW** [comment]
> @PureW maybe this also fixes the clang issues over at [#2750 (comment)](https://github.com/valhalla/valhalla/pull/2750#issuecomment-871672316) ?

Initially getting one error
```
../src/loki/polygon_search.cc:31:19: error: unused variable 'Haversine' [-Werror,-Wunused-const-variable]
static const auto Haversine = [] {
                  ^
1 error generated.
[17/81] Building CXX object src/meili/CMakeFiles/valhalla-meili.dir/map_matcher.cc.o
```

Fixing that, I still get the error in the unittest:

```
[ RUN      ] AvoidTest.TestAvoidShortcutsTruck                                                                                         ../test/gurka/test_avoids.cc:214: Failure                        
Expected equality of these values:                                                                                                     
  avoid_edges.size()                                                                                                                   
    Which is: 0                                                                                                                        
  4                                                                                                                                    [  FAILED  ] AvoidTest.TestAvoidShortcutsTruck (5 ms)
```

File: src/loki/polygon_search.cc (hunk 2 above)
Comment (nilsnolde) [reply src/loki/polygon_search.cc:40]: jep, our rings are expected as clockwise so it fixes counterclockwise rings. also closes open rings if the rings are typed that way (that we do ourselves actually while parsing the request, could remove that tiny bit now). 

I don't remember why, but I had `correct()` in an early version before merging the initial PR and I took it out. couldn't find any commit or so to figure out why I took it out. but since it compiles and tests pass, I'll leave it in (and remove the bit where we close the polygons in the request).

File: src/loki/polygon_search.cc (hunk 3 above)
Comment (nilsnolde) [reply src/loki/polygon_search.cc:94]: oops, I should've specified the `Haversine` function above, forgot that. But apparently it does some deductions from the underlying point type, no idea what that exactly defaults too though. So rather be explicit and put the Haversine strategy there.

File: src/loki/polygon_search.cc (hunk 4 above)
Comment (nilsnolde) [reply src/loki/polygon_search.cc:154]: so the `ei.shape` has `std::vector<PointLL>` type which we register with bg as ring type so that's how it's treated in the bg::intersects call. But of course as an open ring which is the "undefined behavior" part for me.

**Comment by nilsnolde** [comment]
@kevinkreiser thanks for the review, I added haversine perimeter calculation and removed our own ring closing logic when parsing the request.

@PureW the unused-variable warning is gone, forgot to add that function as a strategy.. No idea what to make of that failing test, maybe I'll try clang one of these days

File: src/loki/polygon_search.cc (hunk 4 above)
Comment (nilsnolde) [reply src/loki/polygon_search.cc:155]: When I printed out the avoided edges from a polygon covering only one way I got back like 20 edges before this change. No idea what bg does internally in a situation like that. Now it only prints those 2 DE the polygon really intersects.

**Comment by kevinkreiser** [comment]
this looks good to me. are we saying that compiling with clang fails the tests though?

**Comment by nilsnolde** [comment]
> clang fails the tests

seems so @kevinkreiser . though that's not new with this PR, @PureW reported it a couple of weeks back in that initial PR. Must've somehow been introduced with clang 12.0, no idea what's so compiler-specific about that test.. I'll open another issue about it.

**Comment by PureW** [comment]
> this looks good to me. are we saying that compiling with clang fails the tests though?

Yea, [I'm seeing this](https://github.com/valhalla/valhalla/pull/2750#issuecomment-871672316) I haven't dug into why this is though.

**Review by kevinkreiser — APPROVED** [review]
