### PR TITLE
fixes #1970

### LINKED ISSUE #1970: Protobuf compiler 3.10 generates Costing_Name clashing with valhalla::Costing_Name
TL;TR: When compiling Valhalla's `.proto` files using Protobuf **3.10**, the `protoc` generates `Foo_Name` and `Foo_Parse` functions which clash with existing hand-rolled ones of the very same names (and possibly similar purpose).

Let's consider the problem using the [enum Costing in options.proto](https://github.com/valhalla/valhalla/blob/3176db5363b4a3c678532b8d496274858977776d/proto/options.proto#L33) and [Costing_Name](https://github.com/valhalla/valhalla/blob/3176db5363b4a3c678532b8d496274858977776d/src/worker.cc#L952) function for concrete example.

First, the [valhalla namespace in src/worker.cc](https://github.com/valhalla/valhalla/blob/3176db5363b4a3c678532b8d496274858977776d/src/worker.cc#L889) defines the collection of `Foo_Name` and `Foo_Parse` functions, including the `Costing_Name` function.

Second, compilation of the `options.proto` using `protoc` **3.10** produces the C++ files which contain the following

- `options.pb.h`

    ```cpp
    const std::string& Costing_Name(Costing value);

    template<typename T>
    inline const std::string& Costing_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Costing>::value ||
        ::std::is_integral<T>::value,
        "Incorrect type passed to function Costing_Name.");
    return Costing_Name(static_cast<Costing>(enum_t_value));
    }
    ```

- `options.pb.cc`

    ```cpp
    const std::string& Costing_Name(
        Costing value) {
    static const bool dummy =
        ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
            Costing_entries,
            Costing_entries_by_number,
            13, Costing_strings);
    (void) dummy;
    int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
        Costing_entries,
        Costing_entries_by_number,
        13, value);
    return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                        Costing_strings[idx].get();
    }
    ```

among other `Foo_Parse` and `Foo_Name` definitions.

This leads to the redefinition and link-error, for example, when linking tools against static archive `valhalla.lib`:

```console
valhalla.lib(worker.obj) : 
  error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl valhalla::Costing_Name(enum valhalla::Costing)" 
    (?Costing_Name@valhalla@@YAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Costing@1@@Z) 
  already defined in valhalla.lib(options.pb.obj)
  [C:\projects\valhalla\build\valhalla_run_isochrone.vcxproj]
```

Compilation of `options.proto` with `protoc` **3.2** does not output any such `Foo_Parse` and `Foo_Name` definitions, so no link-error occurs.

The [valhalla-protoc-3.2-vs-3.10.zip](https://github.com/valhalla/valhalla/files/3719101/valhalla-protoc-3.2-vs-3.10.zip) contains full versions of the `protoc`-generated files for comparison:

```
valhalla-protoc-3.10-options.pb.cc
valhalla-protoc-3.10-options.pb.h
valhalla-protoc-3.2-options.pb.cc
valhalla-protoc-3.2-options.pb.h
```

My experience with Protobuf is running short to judge if this is something expected or a compatibility breakage.

------

Currently, Valhalla's CI on AppVeyor (and Azure Pipelines) configurations use the Protobuf **3.10**, but since no tools are currently built, just `valhalla.lib`, the link-error does not occur.
I am preparing PR to add `-DENABLE_TOOLS=ON` (and perhaps `-DENABLE_DATA_TOOLS=ON` too) and that attempt revealed the problem.

### PR DESCRIPTION
**Pull request by kevinkreiser**
this is blocking #1993 

also updates install instructions for bionic, modspatialite doesnt work yet though

### CODE REVIEW

File: valhalla/worker.h [hunk 1]
```diff
@@ -16,19 +16,19 @@ namespace valhalla {
 
 // to use protobuflite we cant use descriptors which means we cant translate enums to strings
 // and so we reimplement the ones we use here
-bool Options_Action_Parse(const std::string& action, Options::Action* a);
```
Comment (kevinkreiser) [inline valhalla/worker.h]: this is the actual change. we rename these functions to avoid name collisions with newer versions of protobuf that actually even in the lite generated code will provide these
