### PR TITLE
Bugfix of issue: Config singleton multiple instantiation issue #4521

### LINKED ISSUE #4521: Config singleton multiple instantiation issue
I wanted to use the new config singleton from valhalla/config.h and found out that it is not a real singleton, it's constuctor was called more than once. ( and, at the second time, I got a valhalla::ConfigUninitializedException() error )

Steps to reproduce (on Linux, Ubuntu): 
- call valhalla::config(_config_json_file_) from your main method (as usual)
- call valhalla::config() from a source file in the main valhalla library ( libvalhalla.a )
- Build and execute your modified valhalla_service/valhalla_... tool. A ConfigUninitializedException will be thrown. 
 
The second valhalla::config() call wants to create a second instance of your config_singleton_t singleton object, but, as it's argment is the default empty string, it will throw this exception. 
IMHO this error is caused by the fact that this "static" instance is not a singleton, one object will be created in each translation unit where config.h is included. 

A (proposed) solution to this problem is to create a config.cc source file, and put the static instance variable there. (checked it, and it worked)

### PR DESCRIPTION
**Pull request by akesmarki**
# Issue

Config singleton multiple instantiation issue #4521
Fixes #4521

## Tasklist

 - [ ] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)
 - [x] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

Attila Kesmarki <attila.kesmarki@nng.com> NNG LLC. 

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

File: src/config.cc [hunk 1]
```diff
@@ -0,0 +1,75 @@
+
+// The MIT License (MIT)
```
Comment (kevinkreiser) [inline src/config.cc:2]: any chance we could move this to the pr description instead of the code? I'd prefer not to have the bloat in the code especially for something so trivial

**Comment by kevinkreiser** [comment]
this was my fault. I think I remember asking the original author to make it a single header... sorry about that totally slipped my mind

File: src/config.cc [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+// THE SOFTWARE.
+//
+
+#include "config.h"
+#include "baldr/rapidjson_utils.h"
+#include <filesystem>
+#include <mutex>
```
Comment (kevinkreiser) [inline src/config.cc:29]: where did this come from?

Comment (akesmarki) [reply src/config.cc]: you are right, it's not necessary, removed

File: CHANGELOG.md [hunk 3]
```diff
@@ -3,6 +3,7 @@
    * REMOVED: needs_ci_run script [#4423](https://github.com/valhalla/valhalla/pull/4423)
    * REMOVED: unused vehicle types in AutoCost and segway; renamed kTruck to "truck" instead of "tractor_trailer" [#4430](https://github.com/valhalla/valhalla/pull/4430)
 * **Bug Fix**
+   * FIXED: Config singleton multiple instantiation issue [#4521](https://github.com/valhalla/valhalla/pull/4521)
```
Comment (kevinkreiser) [inline CHANGELOG.md:6]: i know its slightly confusing but please move this to the bottom of the bug fix list. we order ours from oldest at the top to newest at the bottom of each list. sorry for the annoyance

**Review by kevinkreiser — APPROVED** [review]
this is ready to go, just please move the changelog entry to the end of the bug fix list and make sure to merge master into your branch! thank you!

File: CHANGELOG.md (hunk 3 above)
Comment (akesmarki) [reply CHANGELOG.md]: done

**Comment by akesmarki** [comment]
I'm ready, I hope this PR can be accepted now.

File: src/CMakeLists.txt [hunk 4]
```diff
@@ -184,11 +184,13 @@ endif()
 set(valhalla_hdrs
     ${VALHALLA_SOURCE_DIR}/valhalla/valhalla.h
     ${VALHALLA_SOURCE_DIR}/valhalla/worker.h
+    ${VALHALLA_SOURCE_DIR}/valhalla/config.h
```
Comment (nilsnolde) [inline src/CMakeLists.txt:187]: perfect, just did that in another PR as well, was an oversight in the initial one

File: src/config.cc [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+namespace {
+struct config_singleton_t {
+protected:
+  boost::property_tree::ptree config_;
+
+  config_singleton_t() = delete;
+
+  config_singleton_t(const std::string& config_file_or_inline) {
+    if (config_file_or_inline.empty()) {
+      throw valhalla::ConfigUninitializedException();
```
Comment (nilsnolde) [inline src/config.cc:12]: while you're at it, can we please remove this custom error from the codebase and make it a good ol' `std::runtime_error` with the same message?

**Review by nilsnolde — APPROVED** [review]
it's great, thanks. if you're up for solving my comment while you're at it, that'd be much appreciated. if not, I'll sneak it into one of my PRs

File: src/config.cc (hunk 5 above)
Comment (akesmarki) [reply src/config.cc]: ok, changed it

**Review by kevinkreiser — APPROVED** [review]
