### PR TITLE
Temporary fix for trace_route crash

### LINKED ISSUE #2321: trace_route crash
Encountering a crash with trace_route and narrowed it down to the following:
Line 448 of src/thor/trace_route_action.cc does this:
    auto prev_match_result = match_result_itr++;

On line 458 match_result_itr is used in find_if. However, it is never checked to see if incrementing match_result_itr moves past the end of match_results.

### PR DESCRIPTION
**Pull request by dnesbitt61**
Check match_result_itr after it is incremented to make sure it doesn't iterate past the end of match_results. Note - this is just a quick fix to throw an exception rather than causing a crash. There may be more graceful ways to continue forming the path.

fixes #2321 

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

File: src/thor/trace_route_action.cc [hunk 1]
```diff
@@ -446,6 +446,11 @@ thor_worker_t::map_match(Api& request) {
         // (NOTE that, in between edges may have same edge id with the last edge) right before where
         // discontinuity occurs
         auto prev_match_result = match_result_itr++;
+        if (match_result_itr >= match_results.cend()) {
```
Comment (kevinkreiser) [inline src/thor/trace_route_action.cc:449]: we are in the middle of refactoring this, so i  think this is good enough for now until the refactor lands (which will delete all this extremely error-prone code)
