### PR TITLE
 Fixed instructions when starting on an internal edge

### LINKED ISSUE #1794: Incorrect instructions when starting on an internal edge
## Issue
When starting a route on an internal edge the incorrect instructions are produced.

### Example#1
```
{"locations":[{"lat":39.177814,"lon":-76.847984,"street":"Broken Land Parkway"},{"lat":39.177925,"lon":-76.848099,"street":"Snowden River Parkway"}],"costing":"auto","directions_options":{"units":"miles"}}
```
image

### Example#2
```
{"locations":[{"lat":39.177929,"lon":-76.848114,"street":"Snowden River Parkway"},{"lat":39.177799,"lon":-76.848175,"street":"Snowden River Parkway"}],"costing":"auto","directions_options":{"units":"miles"}}
```
image

## Tasks

- [x] Analyze
- [x] Update logic to fix issue
- [x] Test

### PR DESCRIPTION
**Pull request by dgearhart**
# Issue

Fixes #1794 

### Example#1
image
``` DIFF
< BEFORE
< 1: Drive west on Snowden River Parkway.
< 2: You have arrived at Snowden River Parkway.
> AFTER
> 1: Drive northeast on Broken Land Parkway.
> 2: Turn left onto Snowden River Parkway.
> 3: You have arrived at Snowden River Parkway.
```

### Example#2
image
``` DIFF
< BEFORE
< 1: Drive southeast on Snowden River Parkway.
< 2: You have arrived at Snowden River Parkway.
> AFTER
> 1: Drive west on Snowden River Parkway.
> 2: Make a left U-turn at Broken Land Parkway to stay on Snowden River Parkway.
> 3: You have arrived at Snowden River Parkway.
```
## Tasklist

 - [x] Test
 - [x] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

File: src/odin/maneuversbuilder.cc [hunk 1]
```diff
@@ -836,8 +836,9 @@ void ManeuversBuilder::InitializeManeuver(Maneuver& maneuver, int node_index) {
     maneuver.set_roundabout_exit_count(1);
   }
 
-  // Internal Intersection
-  if (prev_edge->internal_intersection() && !trip_path_->IsLastNodeIndex(node_index)) {
+  // Internal Intersection - excluding the first and last edges
+  if (prev_edge->internal_intersection() && !trip_path_->IsLastNodeIndex(node_index) &&
+      !trip_path_->IsFirstNodeIndex(node_index - 1)) {
```
Comment (kevinkreiser) [inline src/odin/maneuversbuilder.cc]: this is what i would have expected
