### PR TITLE
fix: set NODATA value in geotiff

### LINKED ISSUE #5684: set NODATA value for isochrone geotiff
Porting #5680 I realized that we're hinting at what the NODATA value should be, but we never actually set it. It's also worth noting that it's for some reason not a "standard" geotiff (much less tiff of course) and the usual way is to write a TIFF header entry which signals _GDAL_ the NODATA value.

### PR DESCRIPTION
**Pull request by nilsnolde**
based on #5680 

fixes #5684 

before
image

after
image

### CODE REVIEW

File: test/isochrone.cc [hunk 1]
```diff
@@ -192,7 +192,7 @@ TEST(Isochrones, Basic) {
...
...1,52.095681],[5.070164,52.09878],[5.061846,52.106462],[5.060234,52.10685],[5.05533,52.110937],[5.059321,52.112546],[5.062321,52.109518],[5.063768,52.109489],[5.063819,52.111937],[5.061808,52.112424],[5.057766,52.116937],[5.058695,52.118311],[5.056869,52.118485],[5.056386,52.119871],[5.058321,52.119782],[5.05897,52.118586],[5.06122,52.117836],[5.064004,52.117937],[5.062426,52.118042],[5.062321,52.1191],[5.060321,52.12016],[5.056281,52.119976],[5.054321,52.11823],[5.05036,52.118976],[5.050022,52.117235],[5.0475,52.117116],[5.047321,52.117766],[5.047321,52.11617],[5.049321,52.114042],[5.049475,52.114782],[5.052321,52.114542],[5.053321,52.115561],[5.055664,52.11528],[5.055612,52.113645],[5.053321,52.11155],[5.049195,52.112811],[5.049212,52.113828],[5.046321,52.11377],[5.043321,52.115486],[5.041321,52.115474],[5.03587,52.118486],[5.038321,52.121582],[5.038623,52.119937],[5.039321,52.119889],[5.040321,52.120767],[5.041756,52.119937],[5.04205,52.120937],[5.038526,52.122142],[5.038414,52.122937],[5.038489,52.123768],[5.039656,52.123937],[5.041388,52.125869],[5.041476,52.126781],[5.042321,52.126912],[5.042321,52.127328]],"type":"LineString"},"type":"Feature"}],"type":"FeatureCollection"})";
```
Comment (nilsnolde) [inline test/isochrone.cc:195]: the difference in isochrones is less clear than I hoped for, i.e. it doesn't seem like the new isochrone is _always_ tighter where it's neighboring NODATA values. the only change that I could visually make out is

Image

blue is branch, red is master. IIRC that corner was very often the source of changes..

there's only 1 place where we look at NODATA/`max_value_` in the contouring algo:

https://github.com/valhalla/valhalla/blob/850b2a47a2c68bdf0623065af7d688455f9be603/valhalla/midgard/gridded_data.h#L263-L273

I can't really judge that though.. in the end I don't think we'll create worse shapes than before, just somewhat slightly different.

File: test/isochrone.cc [hunk 2]
```diff
@@ -432,12 +432,12 @@ TEST(Isochrones, test_geotiff_output_time) {
...
-  ASSERT_GT(x, 0);
-  ASSERT_GT(y, 0);
-  ASSERT_EQ(static_cast<int>(min_max[0]), 0);
-  ASSERT_EQ(static_cast<int>(min_max[1]), 660);
-  // ASSERT_EQ(band->GetNoDataValue(), std::numeric_limits<uint16_t>::max());
+  EXPECT_EQ(err, CE_None);
+  EXPECT_GT(x, 0);
+  EXPECT_GT(y, 0);
+  EXPECT_EQ(static_cast<int>(min_max[0]), 0);
+  EXPECT_EQ(static_cast<int>(min_max[1]), 2768);
```
Comment (nilsnolde) [inline test/isochrone.cc:439]: now that it's pretty much unbound to mark cells, it's increasing the max valid values a lot. before the ceiling was a lot lower and it wouldn't be able to go past our determined max_value.

File: test/isochrone.cc [hunk 3]
```diff
@@ -57,7 +57,7 @@ void test_iso_shape_equality(const rapidjson::GenericArray<false, rapidjson::Val
     }
   }
   // TODO: maybe use macro here to have higher tolerance only apply on ARM arch
-  ASSERT_TRUE(test::shape_equality(actual, expected, 41));
+  EXPECT_TRUE(test::shape_equality(actual, expected, 41));
```
Comment (nilsnolde) [inline test/isochrone.cc:60]: changed all the asserts to expects so it's less disruptive/more informative
