### PR TITLE
remove boost::filesytem and boost::system dependencies. also fixes #1437

### LINKED ISSUE #1437: SQLite load_extension syntax doesn't work Ubuntu 18.04
The current syntax for loading the spatialite module does not appear to work on Ubuntu 18.04. It appears to be looking for a filename, not the base object library name. See a transcript of the session below run on my build server for an illustration of the syntax currently employed in the codebase vs the working syntax.

```
sqlite> select load_extension('mod_spatialite');
Error: mod_spatialite: cannot open shared object file: No such file or directory
sqlite> select load_extension('mod_spatialite.so');

sqlite> 
```

### PR DESCRIPTION
**Pull request by kevinkreiser**
this removes quite a lot of our boost dependencies. namely it removes linking for filesystem, system and date_time (this one wasnt used anymore anyway). the bulk of the change was to make everything use our homegrown filesystem library. i needed to add a couple smaller functions and i still have one to add which doesnt seem like too much work.

while i was at it, i got the build working on ubuntu 18.04 specifically by implementing the suggestion here: https://github.com/valhalla/valhalla/issues/1437#issuecomment-458204059

i think we can soon remove the bionic install instructions as that distro should work out of the box after this pr.

more info as to why we want to do stuff like this can be found in these issues: #1465 and
#2009

### CODE REVIEW

File: valhalla/filesystem.h [hunk 1]
```diff
@@ -359,4 +422,7 @@ inline bool remove_all(const path& p) {
   return remove(p);
 }
 
+inline path unique_path() {
+  return path("TODO:");
```
Comment (kevinkreiser) [inline valhalla/filesystem.h]: this should be the only thing left to implement other than the unit tests for it

File: valhalla/filesystem.h [hunk 2]
```diff
@@ -93,6 +110,20 @@ class path {
...
+  return os;
+}
+
+template <class CharT, class Traits>
+std::basic_istream<CharT, Traits>& operator>>(std::basic_istream<CharT, Traits>& is, path& p) {
+  std::string tmp;
+  is >> tmp;
+  p = path(tmp);
+  return is;
+}
```
Comment (kevinkreiser) [inline valhalla/filesystem.h]: need sometihng like: https://github.com/valhalla/valhalla/pull/2008/files on these to handle spaces in the input

File: src/baldr/graphtile.cc [hunk 3]
```diff
@@ -136,22 +149,19 @@ GraphTile::GraphTile(const GraphId& graphid, char* ptr, size_t size) : header_(n
...
   // so we can avoid cases when another thread could read partially written file.
-  auto tmp_location = disk_location + filesystem::unique_path().string();
   auto dir = filesystem::path(disk_location);
   dir.replace_filename("");
 
   bool success = true;
+  filesystem::path tmp_location;
   if (filesystem::create_directories(dir)) {
-    std::ofstream file(tmp_location, std::ios::out | std::ios::binary | std::ios::ate);
+    // Technically this is a race condition but its super unlikely (famous last words)
```
Comment (PureW) [inline src/baldr/graphtile.cc]: :smile:

File: src/baldr/graphtile.cc [hunk 4]
```diff
@@ -137,22 +149,19 @@ GraphTile::GraphTile(const GraphId& graphid, char* ptr, size_t size) : header_(n
...
-  auto tmp_location = disk_location + boost::filesystem::unique_path().string();
   auto dir = filesystem::path(disk_location);
   dir.replace_filename("");
 
   bool success = true;
+  filesystem::path tmp_location;
   if (filesystem::create_directories(dir)) {
-    std::ofstream file(tmp_location, std::ios::out | std::ios::binary | std::ios::ate);
+    // Technically this is a race condition but its super unlikely (famous last words)
+    while (tmp_location.string().empty() && filesystem::exists(tmp_location))
```
Comment (merkispavel) [inline src/baldr/graphtile.cc]: should it be "or"?
```suggestion
    while (tmp_location.string().empty() ||  filesystem::exists(tmp_location))
```

**Comment by PureW** [comment]
Are you looking for a review while it is marked as WIP?

**Comment by kevinkreiser** [comment]
@PureW dont waste time on review at this point. its pretty much done but i just need to knock out a TODO i left in there

File: src/CMakeLists.txt [hunk 5]
```diff
@@ -111,7 +111,8 @@ configure_file(../valhalla/config.h.cmake ${CMAKE_CURRENT_BINARY_DIR}/valhalla/c
 
 set(valhalla_hdrs
     ${CMAKE_CURRENT_BINARY_DIR}/valhalla/valhalla.h
-    ${VALHALLA_SOURCE_DIR}/valhalla/worker.h)
+    ${VALHALLA_SOURCE_DIR}/valhalla/worker.h
+    ${VALHALLA_SOURCE_DIR}/valhalla/filesystem.h)
```
Comment (kevinkreiser) [inline src/CMakeLists.txt]: fixed already in @PureW other PR

File: src/baldr/graphtile.cc [hunk 6]
```diff
@@ -38,6 +37,19 @@ struct dir_facet : public std::numpunct<char> {
...
 constexpr float COMPRESSION_HINT = 3.5f;
+
+std::string MakeSingleTileUrl(const std::string& tile_url, const valhalla::baldr::GraphId& graphid) {
+  auto id_pos = tile_url.find(valhalla::baldr::GraphTile::kTilePathPattern);
+  return tile_url.substr(0, id_pos) + valhalla::baldr::GraphTile::FileSuffix(graphid.Tile_Base()) +
+         tile_url.substr(id_pos + std::strlen(valhalla::baldr::GraphTile::kTilePathPattern));
+}
+
+std::string GenerateTmpSuffix() {
+  // TODO: use /dev/random or similar on windows
```
Comment (kevinkreiser) [inline src/baldr/graphtile.cc]: we can make this more secure/intellegent. i still want to do the right thing here before merging this PR

**Comment by kevinkreiser** [comment]
Sadly clang-tidy is completely mangling the code in the debug build. so much so that the resulting file is just a jumble of spliced together lines of code that isnt even valid syntax... So I'm not really sure what to do about that :(

File: src/mjolnir/hierarchybuilder.cc [hunk 7]
```diff
@@ -140,14 +139,14 @@ void FormTilesInNewLevel(GraphReader& reader,
...
       // where a new node exists
-      uint8_t lowest_level;
       auto f = find_nodes(old_to_new, base_node);
-      if (f.local_node.Is_Valid()) {
-        lowest_level = 2;
-      } else if (f.arterial_node.Is_Valid()) {
-        lowest_level = 1;
-      } else if (f.highway_node.Is_Valid()) {
-        lowest_level = 0;
+      uint8_t lowest_level =
```
Comment (kevinkreiser) [inline src/mjolnir/hierarchybuilder.cc:143]: i wouldnt have changed this but the way we have clang-tidy configured, if you touch a file, it will make you do all the clang tidy things to it regardless of whether it was code you touched or not

File: src/mjolnir/statistics_database.cc [hunk 8]
```diff
@@ -17,45 +19,31 @@ namespace mjolnir {
...
 
   spatialite_init(0);
 
-  sqlite3* db_handle;
-  sqlite3_stmt* stmt;
-  uint32_t ret;
-  char* err_msg = NULL;
-  std::string sql;
-
-  ret =
```
Comment (kevinkreiser) [inline src/mjolnir/statistics_database.cc:32]: this was more clang tidy annoyances

File: src/mjolnir/util.cc [hunk 9]
```diff
@@ -130,14 +129,33 @@ bool shapes_match(const std::vector<PointLL>& shape1, const std::vector<PointLL>
   }
 }
 
+bool load_spatialite(sqlite3* db_handle) {
```
Comment (kevinkreiser) [inline src/mjolnir/util.cc:132]: doing this makes valhalla build out of the box on all the latest versions of ubuntu up to 20.04
