### PR TITLE
Move trace_options parsing to map matcher factory

### LINKED ISSUE #1259: Custom costing_options do not work with trace requests
Valhalla custom costing options currently do not work with `trace_route` and `trace_attributes` requests.

For example, the following request adds a `max_hiking_difficulty` costing_option per https://github.com/valhalla/valhalla/issues/1070#issuecomment-358783988, however neither `trace_route` nor `trace_attributes` respect this.

```json
POST http://localhost:8002/trace_route
{
    "shape": [{
            "lon": -119.5132040977478,
            "lat": 37.745776972676296
        },
        {
            "lon": -119.51333284378052,
            "lat": 37.746133285661
        },
        {
            "lon": -119.5132040977478,
            "lat": 37.746319925111216
        },
        {
            "lon": -119.51356887817383,
            "lat": 37.74662533410542
        },
        {
            "lon": -119.513783454895,
            "lat": 37.746913774776
        },
        {
            "lon": -119.51369762420654,
            "lat": 37.747219181319515
        },
        {
            "lon": -119.51393365859985,
            "lat": 37.74781302376846
        }
    ],
    "shape_match": "map_snap",
    "costing": "pedestrian",
    "trace_options": {
        "turn_penalty_factor": 500
    },
    "costing_options": {
        "pedestrian": {
            "max_hiking_difficulty": 6
        }
    },
    "directions_options": {
        "units": "miles"
    }
}
```

### PR DESCRIPTION
**Pull request by ericrwolfe**
# Issue

This PR updates map matcher factory to properly apply custom `costing_options` and `trace_options` from the default `trace_route` and `trace_attributes` json payloads. Previously, `trace_*` requests would ignore any `costing_options` passed in. Fixes #1259.

## Tasklist

 - [x] add tests
 - [ ] review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Generally use squash merge to rebase and clean comments before merging
 - [ ] Add to release notes in valhalla-docs
 - [ ] update relevant documentation if this is an API impacting change

### CODE REVIEW

File: src/meili/traffic_segment_matcher.cc [hunk 1]
```diff
@@ -10,35 +10,10 @@
...
-  boost::property_tree::ptree parse_json(const std::string& json, const std::unordered_set<std::string> customizable, boost::property_tree::ptree& match_config) {
+  boost::property_tree::ptree parse_json(const std::string& json) {
     boost::property_tree::ptree request;
     try { std::stringstream stream(json); boost::property_tree::read_json(stream, request); }
     catch (...) { throw std::runtime_error("Couln't parse json input"); }
-
-    if(customizable.empty())
-      return request;
-
-    auto match_options = request.get_child_optional("match_options");
```
Comment (ericrwolfe) [inline src/meili/traffic_segment_matcher.cc]: This commit renames the `match_options` object to `trace_options` for consistency with the publicly documented `trace_*` requests, since this code was duplicated both here and in thor's worker. 

I couldn't find any public docs on traffic matching, so I don't know the impact of such a breaking json attribute change. One alternative could be to handle [multiple options here](https://github.com/valhalla/valhalla/pull/1260/files#diff-329096d7bcd764e3019caedc27da61d6R107).

**Comment by dnesbitt61** [comment]
I think that costing options were not included because map-matching uses distance based costing, with a time based validity check to throw away impossible paths if the input has a time component. This last part was only recently added. The main costing method used is the Allowed method to determine if an edge is allowed by the costing mode / travel mode. Most of these are not overriden by costing_options - though bicycle type impacts this as does max hiking difficulty so I do see use there. I am fine with adding this to handle the behavior of which edges are Allowed in the matched path. But I think we need to keep the distance based "costing" for map matching (not sure if you anticipated changing that?)

**Comment by ericrwolfe** [comment]
> But I think we need to keep the distance based "costing" for map matching (not sure if you anticipated changing that?)

From what I've tested, and as far as I am aware, this preserves the existing distance-based costing as before, and merely allows sif to apply custom `costing_options` when supplied and applicable. 

As you've pointed out, this only affects `costing_options` that are used within sif's `Allowed()` method for now. (Although I suppose that in the future, map matching could potentially be able to account for other costing options such as `pedestrian.walkway_factor` or `cycling.use_roads` to prefer certain edge candidates over others, e.g. a cycle path that parallels a main road).

I can open a PR that clarifies this in [the docs](https://github.com/valhalla/valhalla-docs/blob/master/map-matching/api-reference.md#costing-models-and-other-options) accordingly: they currently imply that `costing_options` will apply to trace requests.

Example request:
```json
POST http://localhost:8002/trace_route
{
    "shape": [{
            "lon": -119.5132040977478,
            "lat": 37.745776972676296
        },
        {
            "lon": -119.51333284378052,
            "lat": 37.746133285661
        },
        {
            "lon": -119.5132040977478,
            "lat": 37.746319925111216
        },
        {
            "lon": -119.51356887817383,
            "lat": 37.74662533410542
        },
        {
            "lon": -119.513783454895,
            "lat": 37.746913774776
        },
        {
            "lon": -119.51369762420654,
            "lat": 37.747219181319515
        },
        {
            "lon": -119.51393365859985,
            "lat": 37.74781302376846
        }
    ],
    "shape_match": "map_snap",
    "costing": "pedestrian",
    "trace_options": {
        "search_radius": 65,
        "turn_penalty_factor": 500
    },
    "costing_options": {
        "pedestrian": {
            "walking_speed": 2,
            "max_hiking_difficulty": 6,
            "walkway_factor": 0.5, // time-based costing, not applied
            "step_penalty": 3.0, // time-based costing, not applied
            "use_ferry": 0 // time-based costing, not applied
        }
    },
    "directions_options": {
        "units": "miles"
    }
}
```

I'm mainly trying to bring some consistency to the `/trace_*` requests and the `/route` requests. Right now the edges that are _allowed_ on a `/route` request with custom `costing_options` are not the same as the corresponding `trace_*` request given the same request options.

**Comment by kevinkreiser** [comment]
@ericrwolfe this is my understanding as well wrt to time/distance controlling the results of map matching. actually the metric used has two factors one of which is the distance from input and the other is the time between subsequent positions. in any case i think this is ok!

**Comment by kevinkreiser** [comment]
ill give this a review as soon as i get the time!

File: src/meili/map_matcher_factory.cc [hunk 2]
```diff
@@ -74,9 +87,28 @@ MapMatcherFactory::MergeConfig(const std::string& name,
     }
   }
 
+  std::unordered_set<std::string> customizable;
+  for (const auto& item : config_.get_child("customizable")) {
```
Comment (ptpt) [inline src/meili/map_matcher_factory.cc]: @ericrwolfe @kevinkreiser @dnesbitt61 does it make sense to put the "customizable" filtering logic somewhere else? It's actually like `service_limits` to avoid clients passing insane parameters (e.g. very large `search_radius`) to meili. Having this logic in the factory would surprise users who use meili as a library.

Comment (dnesbitt61) [reply src/meili/map_matcher_factory.cc]: I think this just says which config settings can be overriden in a request. There should be some bounds checking to make sure the inputs are sane.

Comment (ericrwolfe) [reply src/meili/map_matcher_factory.cc]: This checks that the user parameters passed in via `trace_options` have been allowed by the `meili.customizable` array in `valhalla.json`. Most of these parameters are bounds-checked elsewhere, e.g. [`search_radius` is checked against `max_search_radius`](https://github.com/valhalla/valhalla/blob/30768498d75fe3c5d0a171e3aab26dc0f8a5064f/src/meili/map_matcher.cc#L706-L707).

@ptpt do you mean that users who use meili as a service library would wouldn't define the `meili.customizable` property in `valhalla.json` and therefore the "custom" parameters they set wouldn't work as expected?

Comment (ericrwolfe) [reply src/meili/map_matcher_factory.cc]: Thanks @ptpt. I'll defer to @dnesbitt61 or @kevinkreiser on where something like that should live, and whether it makes sense as part of this PR or a follow on.

**Comment by kevinkreiser** [comment]
@ptpt are you good with merging?

**Comment by dnesbitt61** [comment]
I am having trouble getting the traffic_matcher test to pass when trying to merge the conflict. If others have insight into the fix please help!

**Comment by ericrwolfe** [comment]
@dnesbitt61 I just rebased on master and resolved the test/traffic_matcher conflict. Waiting for CI now...

**Comment by ptpt** [comment]
Yes, I'm okay to merge. Thanks for the PR!
