### PR TITLE
fix: docker: only rm transit dir if exists

### LINKED ISSUE #5576: Docker: failing silently when `build_transit=True`
I found the culprit after a lot of confusion:

https://github.com/valhalla/valhalla/blob/d6ab5a7c36458376940e0e313a52a496da5b64e1/docker/scripts/configure_valhalla.sh#L37

I figured this could be the problematic line since I could never enter the following `if` block by mapping nonsense to `/gtfs_feeds`. Then I realised the directory was never created, so this could actually be an issue. I don't understand why this bloks though, since stdout is sent out to `/dev/null`. Still, after creating a custom image by removing this line, I managed to get a container up and running (well, it crashes at `valhalla_convert_transit` but at least I have logs to debug now).

### PR DESCRIPTION
**Pull request by TLouf**
fixes #5576 

Went the explicit way, never hurts!

### CODE REVIEW

File: docker/scripts/configure_valhalla.sh [hunk 1]
```diff
@@ -34,8 +34,10 @@ if [[ "${build_elevation}" == "True" ]] || [[ "${build_elevation}" == "Force" ]]
 fi
 # if there's no transit tiles yet, but it should build transit, then do that; or force and remove
 if [[ "${build_transit}" == "Force" ]] || (! [[ -d ${TRANSIT_DIR} ]] && [[ "${build_transit}" == "True" ]]) || ([[ $(find ${TRANSIT_DIR} -maxdepth 1 -type d | wc -l) -eq 1 ]] && [[ "${build_transit}" == "True" ]]); then
-  rm -r ${TRANSIT_DIR} 2> /dev/null
   do_transit="True"
+  if [[ -a ${TRANSIT_DIR} ]]; then
```
Comment (nilsnolde) [inline docker/scripts/configure_valhalla.sh]: Better "-d", -a is deprecated

**Review by nilsnolde — CHANGES_REQUESTED** [review]
